### ISSUE TITLE
How to properly handle onAborted in a try/catch?

### ISSUE THREAD

**Issue by markg85** [uNetworking/uWebSockets.js#1016]
Hi,

I'm aware of the [video streamer example](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/VideoStreamer.js) that is "explaining" how to handle onAborted.

That solution might be suitable for streaming purposes but is imho huge overkill in a situation where you **just** want to handle an async call.

This should work:
```javascript
const app = uWS.App({
// ...
})
.get('/example', async (res, req) => {
  try {
    // await on some function that is going to write something
    await someFunc(req, req)
  } catch (error) {
    // or when the function fails, write an error
    res.writeStatus('404 Not Found').end(`Some message\n`);
  }
})
.listen(PORT, (token) => {
  if (token) {
    console.log('Listening to port ' + PORT);
  } else {
    console.log('Failed to listen to port ' + PORT);
  }
});
```

The above example is shortened a big for simplicity.

Note that there is no "res.onAborted" handler anywhere. That's intentional.
This should be handled with the catch.

However, the current workings of this library make it so that either of the following isn't working:
```javascript
.get('/example', async (res, req) => {
  res.onAborted(() => {
    res.writeStatus('404 Not Found').end(`Some message\n`);
  });

  try {
    // await on some function that is going to write something
    await someFunc(req, req)
  } catch (error) {
    // or when the function fails, write an error
    res.writeStatus('404 Not Found').end(`Some message\n`);
  }
}
```

nor does this one work:
```javascript
.get('/example', async (res, req) => {
  try {
    // await on some function that is going to write something
    await someFunc(req, req)
  } catch (error) {
    // or when the function fails, write an error
    res.onAborted(() => {
      res.writeStatus('404 Not Found').end(`Some message\n`);
    });
  }
}
```

Having the try/catch case work **without** the requirement to write a load of extra boiler plate code like in the streaming example would be super helpful! Currently this is kinda putting me of from using this library at all as webserver replacement because it's so darn sensitive to getting things just exactly right.

Note that this is just one of a couple issues i have with this library. The others being:
1. The requirement to wrap your handler before you can call your own function (something with scoping?)
2. The cork wrapper for every output (even the examples get this wrong btw)

Those 3 combined make me wonder if the added complexity of using this library is worth it...

**Comment by uNetworkingAB** [comment]
It's not my task to persuade you, esp. not when you haven't made the effort to read the docs and user manual and/or not taken the time to understand it.

In any case, none of those snippets make any sense, they don't even make sense for what would be Express code, since you aren't even wrapping writeStatus in try/catch:

>   } catch (error) {
    // or when the function fails, write an error
    res.writeStatus('404 Not Found').end(`Some message\n`);
  }

Even if we pretend the library would work like Express (it doesn't), the above snippet doesn't handle writeStatus/end failure.

**Comment by markg85** [comment]
Please do share your links to the relevant onAborted places.
All the [documentation](https://unetworking.github.io/uWebSockets.js/generated/interfaces/HttpResponse.html#onAborted) says is:
> Every HttpResponse MUST have an attached abort handler IF you do not respond to it immediately inside of the callback. Returning from an Http request handler without attaching (by calling onAborted) an abort handler is ill-use and will terminate. When this event emits, the response has been aborted and may not be used.

Which isn't really helpful at all.

> In any case, none of those snippets make any sense, they don't even make sense for what would be Express code, since you aren't even wrapping writeStatus in try/catch:

That would be even more confusion from a code point of view.
You'd effectively get a try/catch block within the catch block. Surely you don't find that pretty code, right?

Perhaps you can share how, in your view, this code should be written?
Surely not like the streaming example?

**Comment by uNetworkingAB** [comment]
You already have examples for it: https://github.com/uNetworking/uWebSockets.js/blob/master/examples/AsyncFunction.js

**Comment by markg85** [comment]
Granted, the [AsyncFunction example](https://github.com/uNetworking/uWebSockets.js/blob/70a1fb75e7eeb512d5b8ab95143e37764fe26cc2/examples/AsyncFunction.js) is more useful though it too fails to demonstrate proper use of try/catch along with this library. It might be worth considering to reword the documentation for `onAborted` to be more helpful and **link** to the relevant examples. That would be much more valuable and helpful then the current cryptic message.

Perhaps the [try/catch/finally](https://www.programiz.com/javascript/try-catch-finally) approach is more suited for this library? As http responses can perhaps more appropriately be handled in that statement.

**Comment by porsager** [comment]
@markg85 you don't understand what onAborteded is. 

onAborted is called if the request is dropped. That means you are unable to take ANY action related to the request, because it doesn't exist!

The reason you then have to set it for anything async is because at any point the request could be aborted — and trying to do anything with a request that doesn't exist doesn't make any sense.

Knowing that you must be able to see it doesn't make any sense to try to respond with 404 to a request that doesn't exist.

You would probably be better of not using uWebSockets, because any perfomance gain it could give you would be ruined by the code you write if you don't understand it.

**Comment by uNetworkingAB** [comment]
> though it too fails to demonstrate proper use of try/catch along with this library

The library doesn't use exceptions. That's why none of the examples use try/catch

**Comment by markg85** [comment]
> @markg85 you don't understand what onAborteded is.

I do though i admit my initial example did a great job at making you think i don't get it. I should've set `res.aborted = true;` in it's body instead of `res.writeStatus('404 Not Found').end(`Some message\n`);`  Which i then copy/paste wrong everywhere. Sorry for that unintended confusion.

Fact remains that **without** an async function i don't have to worry about `onAborted`.
And with an async function, however simple it is, i now **need** to handle `onAborted`.

This to me smells like a technical issue in uWebSockets that should be solved internally.
V8 has ways in the C++ side to check for the execution state of a promise. Use that and remove the need to fiddle with onAborted from a library user point of view. Everybody wins in that. You don't get bug report about vague cryptic messages and your users don't need to be bothered by handling internal library details in user code. win-win in my opinion.

**Comment by mustafa519** [comment]
`onAbort` is not the thing that you can always control. The client can close the connection without a reason. So, you need to stop the logic if there is a function which is executing at that moment. That's how to use `onAborted` helper rather than catching the error.

A few recommendations from my experiences;

- Split all the logic as three parts in your mind as start, handle, end.
- Never use an async wrapper on the start and the end parts. `onData` doesn't support async wrappers, and corking is painful in the async context.
- Corking is intended for batch writing purposes like writing something one by one to the response, you send them all in a batched write. Node.js also supports cork somewhat, but nobody uses.
- This is the kind of webserver that you always wanted to know what was going on in the behind of the scenes which is pretty low level, rather than battery included frameworks.

I feel you that it's annoying until get the logic what's going on. However, you'll accept why it has to be done like that when you realize the things.

And yeah, I agree with you that the documentation is not enough, especially if you don't have a low-level background of HTTP. That's why I had to have read at least 10 pages of discussions and 5+ pages of issues in ten days to get the tiny details.

**Comment by markg85** [comment]
Thank you for your response @mustafa519!

> Never use an async wrapper on the start and the end parts. onData doesn't support async wrappers, and corking is painful in the async context.

That is irrelevant in this case. You intent the streaming case, i don't. I just want to send a small - byte-sized, literally - response. It just so happens that i'm using an async function to get the data for that response which is giving me the annoyances of this library.

Even with a low-level background the documentation is cryptic at best. Written with assumption that you know when you're active in the http and even network stack. You can't expect users of this library to know that kind of low-level detail.

> @uNetworkingAB You could make the lib have a default onAborted handler but then non-async requests would be slower as you would need to capture a v8::UniquePersistent of the HttpResponse object every time. And making the lib slower is not a goal, esp. not when the most important usages are almost exclusively non-async. The idea can be benchmarked though, but I already know from experience there will be a measurable cost

I think it's safe to assume that most people using this library use async to get the data to respond. I'd consider a on-par performance for async and a (small) degredation for non-async a worthwhile trade off.  You can benchmark in ideal happy-day scenarios with no async but that's not the reality in how the library will be used.

**Comment by uNetworkingAB** [comment]
> You can benchmark in ideal happy-day scenarios with no async but that's not the reality in how the library will be used.

I have NDA and all that, but TLDR I know exactly how the high value users use it, and it's exceedingly non-async

**Comment by markg85** [comment]
I can see that for the streaming case.

Not for the request -> response case. Say to render a page or whatever. That data always comes form some mechanism and that is nearly always async. That all years ago transitioned from pre-promise-standard (custom promises) to now standardized promises.

**Comment by uNetworkingAB** [comment]
Even though you are _very_ arrogant, it makes me think of ways to solve the issue. I think onAborted can be set by the lib, by default, without destroying perf. if there are some changes to the C++ side. I have some ideas, most likely a v21 kind of change. onAborted behavior would need to change from per-request to per-connection (or per-request) and be set once at connection time (the default behavior).

**Comment by mustafa519** [comment]
@markg85 we're actually using the CPP wrapper of uWebsockets. So, porting it to node.js is also painful. @uNetworkingAB has also limited choices to make it work in node.js since they use entirely different codebases.

Tbf, async logic is slower than callbacks. So, I'd recommend you to use promises only on the blocking operations or in the handler part that you're going to prepare all the request/response logic inside. All the executions already running in the node.js event loop like promises. The main goal is not to block the loop(main thread). So, non-async functions will be always faster than promises unless you're not blocking the main thread.

Since the main goal is performance rather than easy to use, try to think different when you work on uws.


```js
function start(res, req)
{
  // any request request implementations
  req.onAborted(() =>
  {
    // We don't know why request is aborted however we know request is really aborted.
    res.aborted = true;
    console.log('Request aborted for some reason. So time to cleaning up the things.');
  });
}

async function handler(res, req)
{
  // db
  // session
  // any app related logic here
  res.body = 'A node.js server would never be that fast without uws!';
}

function end(res, req)
{
  res.cork(() =>
  {
    res
      .writeStatus(res.status || 200)
      .end(res.body);
  });
}

function error(e)
{
  // catch all the errors here
  res.status = 500; // Internal Server Error
  end(); // end with error
}

function request(res, req)
{
  try
  {
    start(res, req);
    handle(res, req)
      .then(() =>
      {
        // Here is not in the async context
        // So everything is going to as expected
        // Unless request aborts
        if (!res.aborted)
        {
          end();
        }
      })
      .catch(error);
  }
  catch (e)
  {
    error(e);
  }
}

const app = uWS.App()
  .any('/*', request)
  .listen();
```

I also wouldn't want the documentation to get improved that because you need to learn the things carefully that you'll need to use them in every logic. If there are copy/paste examples, you start faster, however you'll get stuck eventually without knowing the logics.

On the other hand, I don't want express guys who don't care what are the behind of the scenes to use this masterpiece without investing something useful. Otherwise, this awesome work would lose its actual value within its contributors as well.

So, IMHO use uws if you're really willing to do investment for the project and your knowledge too.

**Comment by uNetworkingAB** [comment]
Re. documentation - maybe time to ask chatgpt4 to rewrite it lol

**Comment by markg85** [comment]
> Even though you are very arrogant,

My pleasure! You have a tendency to be just that (and yes, I've seen a lot of replied from you, you've mastered the skill of arrogance). While it wasn't my intent i'm glad i could return the favor this time ^_^

@mustafa519 Thank you for that helpful response! That approach looks very c'ish to me. Not a fan of that, especially if the more user friendly libraries can do the same in just a couple lines of code. I know, performance... That is where things get interesting. I'm sure that you can get a user experience like fastify and express but with the performance of uws. Thing is, it surely requires a lot of work from the uws devs to find ways and mechanisms to neatly hide the current interface in something that is more akin to the others without performance degradation. That takes a lot of skill and time to get right so i totally get it if they don't want to do that. However, their "batteries included" claim on uws (the C++ library github page) does seem to sell it as "user friendly" which is only selectively the case. Do note that this is the case in both paths (async and callback), it's just much less of an issue in callbacks.

Lastly, we could also just say that uwebsockets should be used for what it's name implies. Websockets.
It supports being a webserver but perhaps it's not the best tool for the job. I'm also using it for actual websockets and there it's an absolute marvel!

**Comment by uNetworkingAB** [comment]
If you want an interface like the others, why aren't you just picking up any of the wrapper projects that give you exactly this? For instance HyperExpress is already providing you with the Express interface. Those wrappers give you exactly what you want.

**Comment by uNetworkingAB** [comment]
> I'm sure that you can get a user experience like fastify and express but with the performance of uws.

The implied logical meaning of this claim is that, the limitations uws imposes (such as zero-copy, zero-allocation flows), are not motivated and that your five second consideration is superior to my 8 year experience in making this project.

What you say is that, the local optima in terms of simplicity vs. performance is entirely invalid and that there is a local optima that is vastly superior to whatever uws gives you.

I would very much like to see such a project. Like mentioned, there are many such supposed projects, but they all perform significantly worse. But I am listening, your five second consideration clearly is superior.

It's sheer arrogance.

> However, their "batteries included" claim on uws (the C++ library github page) does seem to sell it as "user friendly" which is only selectively the case.

It's your subjective opinion about a subjective classification

**Comment by uNetworkingAB** [comment]
I mean the more I think of it, the level of delusion and ridiculousness blows my mind. You understand that, Express is slow as shit? The interface is designed entirely without any shred of performance thought and all of these IncomingMessage objects and ReadableStream objects are heavy as the sun? And you expect to just magically make it, way faster, without restricting the interface? It's grand delusion and a level of brain smoothness that competes with biden himself, who hasn't had oxygen in his brain since 1987. Pure delusion
