### ISSUE TITLE
Async performance got slow after 15.5.0

### ISSUE THREAD

**Issue by mattiasewers** [uNetworking/uWebSockets.js#105]
For some reason performance got way worse after version 15.5.0

Tested with wrk on ubuntu 18.04:
- 15.5.0 using examples/AsyncFunction.js:  177k req/sec
- 15.8.0 using examples/AsyncFunction.js:  32k req/sec

**Comment by alexhultman** [comment]
Node.js has bugs we cannot fix, so to keep it stable we have to refrain from tweaking V8 for the better.

**Comment by alexhultman** [comment]
https://github.com/nodejs/node/blob/d35af56e5f3b1334c4360dbf8a013d0c522fe5f8/src/api/environment.cc#L191

I'm banned from Node.js so I cannot fork, PR, star or create issues there. If you want to make a test, you can fork it, swap that argument for MicrotasksPolicy::kAuto. If you then PR that change to Node.js repo they will run CI tests and we can see if that makes Node.js crash or fail.

**Comment by mattiasewers** [comment]
@alexhultman ok, will do!

**Comment by mattiasewers** [comment]
https://github.com/nodejs/node/pull/26755

**Comment by alexhultman** [comment]
This change is the only difference solving #79 and it's the only thing reverted in recent versions.

**Comment by alexhultman** [comment]
Let's wait and see if the tests pass or not, maybe this works and can be enabled again. I'm still not sure this was crashing.

**Comment by mattiasewers** [comment]
@alexhultman hmm it seem to have failed...

**Comment by alexhultman** [comment]
Okay, good to know. Normally I wouldn't care about their tests, but in this case I must keep this reverted until I know exactly what caused reported crashes. If it turns out I can enable this again, I will do so.

This ordering test should report 0-7 if I understand it correctly. Not that we care about this rule, it's a stupid and pointless test that promotes the writing of terrible code.

https://github.com/nodejs/node/blob/master/test/addons/make-callback-recurse/test.js

```
AssertionError [ERR_ASSERTION]: verifyExecutionOrder(2) results: 0,1,2,7,3,4,5,6
```

**Comment by mattiasewers** [comment]
@alexhultman yes that's how I understand it, let me know if you need help testing.

**Comment by alexhultman** [comment]
I did some benchmarks just because I wanted to validate my concerns with Node.js bloat.

This:

```
async function nextTickFast(cb) {
	await (() => {
		cb();
	});
}
```

Is using the standard V8 queue and runs about 3x as fast as process.nextTick in the following benchmark:

```
function benchmark() {
	nextTick(() => {
		if (++sum < 10000000) {
			benchmark();
		} else {
			console.log(sum);
		}
	});
}

benchmark();
```

While doing pretty much the exact same thing. This of course has been something I have told them about for 3 years now but their approach is to make things as complicated and bloated as possibly can be.

They should really just drop all of their hacky nonsense and go with the most simple solution - then we addon makers could use standard V8 code and not have to deal with all this hacky hack hack nonsense.

**Comment by alexhultman** [comment]
Okay, never mind that thing before, it was completely broken.

However, I found that doing this:

// do once, keep for ever
const resolved = Promise.resolve();

// do this instead of process.nextTick
resolved.then(cb);

Was 2x the speed of process.nextTick and actually works

**Comment by girng** [comment]
> https://github.com/nodejs/node/blob/d35af56e5f3b1334c4360dbf8a013d0c522fe5f8/src/api/environment.cc#L191
> 
> I'm banned from Node.js so I cannot fork, PR, star or create issues there. If you want to make a test, you can fork it, swap that argument for MicrotasksPolicy::kAuto. If you then PR that change to Node.js repo they will run CI tests and we can see if that makes Node.js crash or fail.

Lol, that's so pathetic.   I reported a bug where  npm install  nuked my entire node_modules folder. I got a 10 day suspension for arguing with them

**Comment by alexhultman** [comment]
Okay I've fixed two other crashes in this release, and I haven't heard back from those reporting **this** crashing so I'll just restore this back for now and hope it was due to the other crashes that's now fixed.
