### ISSUE TITLE
Poor performance on TechEmpower benchmark

### ISSUE THREAD

**Issue by VinnyVicious** [uNetworking/uWebSockets.js#1066]
On the TechEmpower benchmark, uWebSockets.js performs terribly: 
https://www.techempower.com/benchmarks/#hw=ph&test=fortune&section=data-r22

Less effective than php and nginx or https://github.com/just-js/just

Any ways to circumvent that?

**Comment by leeoniya** [comment]
this is comment from the author about it:

https://github.com/uNetworking/uWebSockets/issues/835#issuecomment-465591796

**Comment by VinnyVicious** [comment]
Thank you!

**Comment by uNetworkingAB** [comment]
TechEmpower is a database benchmark. It doesn't benchmark web servers.

The only test that benchmarks nothing but the web server is the "plaintext" test. Here you see uWebSockets.js is at 52nd place. Given that uWebSockets.js is known to have the performance of, at best, 60% of non-Node.js, C++ uWebSockets - we see that 4648856/7013961 = 66% which is better than the expected 60%.

In other words, C++ uWebSockets would score 1st place or insignificantly different from the 1st place. Even if uWebSockets would be, say 10th place, doesn't matter since most TechEmpower top contestants are non-standard, insecure and broken, minimal hacks that nobody could ever use in any kind if production system.

uWebSockets scores among 1st placers while being entirely standards compliant, with URL routing, with SNI routing and with a security trusted by more than half a decade in production systems.

I have not added uWS to TechEmpower and I have no idea why someone added uWS.js but not uWS. It's not my concern.

just-js is not Python or JavaScript, it's a discontinued minimal V8 C++ host that is now deprecated and only was there to win these kinds of benchmarks without any kind of stability, usability or security. It's faster because it doesn't use node::MakeCallback in order to properly integrate with Node.js. This is why "Alien mode" was so much faster for uWS.js: https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.25.0

**Comment by leeoniya** [comment]
> just-js is not Python or JavaScript, it's a discontinued minimal V8 C++ host that is now deprecated and only was there to win these kinds of benchmarks without any kind of stability, usability or security

the author is working on something that aims to be closer to those goals: https://github.com/just-js/lo

**Comment by uNetworkingAB** [comment]
Whatever just-js do, is irrelevant for this project. It's absolutely obvious, from 10 years back, that any Node.js addon that needs to integrate with node::MakeCallback is going to be slower than a raw V8 host project (essentially a new runtime like Deno, Bun) that skips all that AsyncHooks bloat in Node.js.

But because this project is 8 years old, and in production for more than half a decade (probably 7 years now), it's not in our interest to compete with these hacks. uWS.js operates in the Node.js universe. It's a Node.js project.

The point of uWS.js is not to beat raw C++ projects (that's the point of uWS), the point of uWS.js is to beat other Node.js/Deno/Bun projects: https://github.com/SaltyAom/bun-http-framework-benchmark?tab=readme-ov-file#results

And we've done that without interruption for 8 years now, and will continue to do so until Node.js gets deprecated.

**Comment by uNetworkingAB** [comment]
Even for being a database test, uWebSockets.js score 75th and Bun score 116th on that linked Fortunes test. 75th of 496 is 84th percentile. I don't see how a standards compliant and complete Node.js composition scoring 84th percentile, above Bun, is "poor performance".

This just-js thing is 6 source files, less than 500 lines in each, mostly hacked together minimal nonsense that nobody can ever use for anything.

You do know that uWebSockets.js can operate as its own host, right? We did this many years before Bun came, but nobody cared about it.

**Comment by uNetworkingAB** [comment]
"just-js" or "lo" will never be anything more than some garage hacking session. They use V8, we use V8. The absolutely biggest overhead and limitation uWebSockets.js has is node::MakeCallback and even if it is slow, we still use it to be fully compatible with the Node.js ecosystem.

If I wanted to hack something up just to beat "lo" in benchmarks, I could easily do so. I already have tested an idea I call "MessageBatch" which delivers small HTTP requests/responses via a big circle buffer as copies, in one go. So that JS/C++ calling would be 1 single roundtrip.

This boosts performance for small requests by **a lot**, but I dropped the idea since it breaks away from underlying C++ uWebSockets API which I didn't want to (I want uWebSockets.js to be exactly the same API as uWebSockets, and I won't change how uWebSockets works just to satisfy a wild JavaScript optimization that don't apply to C++).

If anyone cares for performance, they better just move to the underlying uWebSockets, which beats any "just-js" or "lo" effortlessly.

Spending so much time optimizing for JavaScript is fooling yourself, as all you're doing is finding ways for how you can minimize the drawbacks of using JavaScript in the first place.

**Comment by uNetworkingAB** [comment]
There are so many cheats you can do. First off you can add the ability to register a ArrayBuffer rather than a function. Then everything would stay in C++ land and your Hello world benchmark would be almost double the speed:

App.get("/", "Hello world!");

Or you add some basic formatting script that is way simpler than JS, like a formatting string where it can add the value of headers and so on.

So all benchmarks that only require simple echoing of the stuff given in the request would entirely avoid JS.

Then you would win all techempower benchmarks

**Comment by uNetworkingAB** [comment]
If you pass it a template string like Mustache and have the variables come from the request itself you can program all kinds of benchmark winners without even going to JS

**Comment by uNetworkingAB** [comment]
"Hello your user-agent is: %user-agent" as formatting string would make a dynamic response with your web browser user agent without even going to JS

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets.js/commit/ba4ae133d0681b86f98db40d11c9426c154f7df8

This adds ability to do App.get(pattern, responseString); as a way to completely avoid calling into JS. This will boost performance in simple benchmarks by close to 100%. This string can be further made dynamic with %req.query(key), %body, %req.header(key) kind of dynamic formatting.

**Comment by porsager** [comment]
Haha.. This feels like the time when KRS One released Step Into a World and put all the whack rappers in their place.. gj

**Comment by uNetworkingAB** [comment]
The ideal interface would be builder pattern to build a chain of functions that can be run through without JS, in the same style as the functions to normally call with HttpResponse:


Instead of a lambda in which JS code calls C++ functions on HttpResponse, you create a Response like so:

App.get(pattern, new Response().writeHeader("my header", "my value").write("Your user agent is: ").writeHeaderValue("user-agent").end();

That is, you just provide JS functions to chain C++ functions together to then be executed entirely in C++ land for every response. It's like you provide the AST of a simple language.


Or... you just provide a formatting string where you can have "action entries" that write headers to the response like %!key: value.

**Comment by uNetworkingAB** [comment]
The practical goal would be to be able to express this server without using any JS functions:

https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Benchmarker.js

It's definitely possible.

**Comment by uNetworkingAB** [comment]
They are pretty much like these:

	// "%(content-type=text/plain)Hi"
	// "%(content-type=text/plain)%(x-powered-by=benchmark)%param(id) %q(name)"
	// %(content-type=application/json)%body

But this syntax looks like crap and needs builder-pattern helpers to create this string from nicer calls. You can even make that builder in simple JS.

Then the top one is new Response().writeHeader("content-type", "text/plain").end("Hi"); which just evaluates to the string "%(content-type=text/plain)Hi" which gets parsed by C++ in hot path. Simple. You don't even need human readable escapes like % but instead they can be binary escapes that require no seeking.

**Comment by uNetworkingAB** [comment]
This will look fking amazing:

App.	.get('/id/:id', (res, req) => {
		res.writeHeader('content-type', 'text/plain')
			.writeHeader('x-powered-by', 'benchmark')
			.end(`${req.getParameter('id')} ${req.getQuery('name')}`)
	})

becomes:

	.get('/id/:id', new uWS.Response().writeHeader('content-type', 'text/plain').writeHeader('x-powered-by', 'benchmark').writeParameterValue("id").write(" ").writeQueryValue("name").end());

and is like, 100% faster.

**Comment by uNetworkingAB** [comment]
In my benchmark, this is now 205% the speed. So 105% boost by not calling JS for simple responses. So all I need now is add these "escape sequences" and uWS.js can win every fucking benchmark under the sun.

**Comment by uNetworkingAB** [comment]
Check this DeclarativeResponse that builds the binary instructions for C++ side to produce the response without calling into JS:

```
class DeclarativeResponse {
    constructor() {
      this.instructions = [];
    }
  
    // Utility method to encode text and append instruction
    _appendInstruction(opcode, ...text) {
      this.instructions.push(opcode);
      text.forEach(str => {
        const bytes = new TextEncoder().encode(str);
        this.instructions.push(bytes.length, ...bytes);
      });
    }
  
    // Utility method to append 2-byte length text
    _appendInstructionWithLength(opcode, text) {
      this.instructions.push(opcode);
      const bytes = new TextEncoder().encode(text);
      const length = bytes.length;
      this.instructions.push((length >> 8) & 0xff, length & 0xff, ...bytes);
    }
  
    writeHeader(key, value) { return this._appendInstruction(1, key, value), this; }
    writeBody() { return this.instructions.push(2), this; }
    writeQueryValue(key) { return this._appendInstruction(3, key), this; }
    writeHeaderValue(key) { return this._appendInstruction(4, key), this; }
    write(value) { return this._appendInstructionWithLength(5, value), this; }
    writeParameterValue(key) { return this._appendInstruction(6, key), this; }
  
    end(value) {
      const bytes = new TextEncoder().encode(value);
      const length = bytes.length;
      this.instructions.push(0, (length >> 8) & 0xff, length & 0xff, ...bytes);
      return new Uint8Array(this.instructions).buffer;
    }
  }
  
  // Example usage
  const response = new DeclarativeResponse()
    .writeHeader("key", "value")
    .writeBody()
    .writeQueryValue("queryKey")
    .writeHeaderValue("headerKey")
    .write("genericValue")
    .writeParameterValue("parameterKey")
    .end("hello world");
  
  console.log(new Uint8Array(response));
```

**Comment by uNetworkingAB** [comment]
Yeah this already works and has ridiculous performance. Will be in next release. Looks like 250% and you can easily express that whole Benchmarker.js with it. This thing is going to crush all known benchmarks by a lot

**Comment by uNetworkingAB** [comment]
Holy fuck these two are already working:

```
	uWS.App()
	.get('/', new uWS.DeclarativeResponse().writeHeader('content-type', 'text/plain').end('Hi'))
	.get('/id/:id', new uWS.DeclarativeResponse().writeHeader('content-type', 'text/plain')
					.writeHeader('x-powered-by', 'benchmark')
					.writeParameterValue("id")
					.write(" ")
					.writeQueryValue("name")
					.end())
```

**Comment by uasan** [comment]
You can add support for promises to the declarative interface?
Then maybe something cool will come out instead of a joke.

**Comment by e3dio** [comment]
Doesn't seem like a joke to me, I have many static routes

**Comment by uNetworkingAB** [comment]
I was thinking stuff that is semi-static could use them such as serveFileFromParameter("base path", "parameter") and similar. And the more benchmarks you can implement (all Hello World benchmarks can use them) the better you climb in these nonsense, cheating lists. I mean, just the PR boost itself is major win and if you can even motivate the existence for these things with the serveFileFromParameter support, they do have at least one use.

Look at Nginx - it's all declarative non-programmable unless you pair it with some scripting language.

But even for cases where you need to serve a simple web page, you can already do new DeclarativeResponse.end(fs.readFileSync("the file to serve")) and get top performance.

**Comment by uNetworkingAB** [comment]
You could even have SQL queries and Moustache templating of those fetched SQL entries. It's pretty much open for anything, if it is common enough.

**Comment by porsager** [comment]
If this means you'd have an incentive to make support for sendfile with kTLS on linux I might wee my pants a little!

I know you often mention it's not interesting because people are running behind a reverse proxy, but I think that would change if uWS is suddenly the fastest at static file serving as well!

**Comment by porsager** [comment]
If not, let me know a price range you'd be in for adding it - might be something we'd consider sponsering.

**Comment by uNetworkingAB** [comment]
One thing that is interesting about just-js is that, even if the thing is a complete dumpster fire in terms of quality (I've looked at the code, it stinks in every way) - it does have one thing going for it:

Node.js, Bun, uWS.js all have a general assumption in common, to varying degrees: native code is faster than JS code. This is, by all means true, by a lot. Especially the more complex the solution is. But what they all miss is that, for simple benchmarks, the overhead of calling JS callbacks from within native code is gigantic in V8 (well, I've known this for 10 years).

The reason DeclarativeResponse is 205% the performance of a simple JS lambda formatting the response is because DeclarativeResponse never calls into the JS callback.

50% of total performance is lost in that one, single invocation of the JS callback.

With just-js, the design is the opposite - as little as possible is native code, and the most micro platform possible is exposed to JS. The entire event-loop, HTTP, timeout is written in JS using raw epoll, timerfd, etc.

This absolutely sucks for anything complex, and can never scale to anything production ready, but it does mean that for ultra simple, pipelined benchmarks, it skips most of the overhead of native/JS calling.

For example, the HTTP pipelined benchmark really only does 2 native calls: read chunk from socket, write chunk to socket. That's 2 calls for the entire benchmark, rather than at least 2 calls for every single request.

This means that just-js essentially has the benefit of my "MessageBatch" feature that I mentioned above.

The performance of JS runtimes in simple benchmarks are essentially dominated only by how many times the runtime needs to jump from JS to native land and back. For Node.js, as they have chosen the most moronic design possible, they do a ton of jumping back and forth. That's why it performs the worst with their built-in HTTP server. They never understood this simple fact, and still believe in this utopia of "let's write the parser in assembly". They never understood a shred of performance, never will.

For Bun, most is native code but still there is some jumping.

For just-js, there is almost no jumping, making it way faster for simple benchmarks. But this also means that, eventually, when there is more complexity involved such as SSL, compression, it will take a bigger hit by having to make calls into native land more often. So it's going to harm performance for non-ridiculous cases.

uWS.js is 100% native. There is no JavaScript code at all. There is no jumping back and forth along the way. This means it is fast for complex cases but take a significant hit every time it needs to call into JS to handle a simple request. For simple benchmarks, this cost dominate.

In essence, V8 is a performance liability, a problem, and there are only partial workarounds. All workarounds have drawbacks, none of them are perfect. The only thing we know for sure is that Node.js picks all of the drawbacks and none of the benefits.

Conclusion still is - anything performance critical must be written in a real language that isn't a script. Rust, C++, to some degree Java, Golang and C# are possibilities. JavaScript can never be an optimal solution to a performance problem.

**Comment by uNetworkingAB** [comment]
just-js kind of reminds me of wasmer / wasmtime but worse. They have the same design: a minimal native platform (WASI) and then V8 atop. The difference of course is that wasmtime implements the top part using webassembly-compiled Rust/C++, so it doesn't suck in performance for complex problems.

But then, what is the point of using V8 at all, when all you do is write Rust/C++ code either way. It just reverts back to the same old solution we've had since the dawn of time: use systems programming languages if you want performance.

I swear, this whole V8-runtime thing is one big marketing ploy. We all know the solution but are too lazy to make it happen.

/ rant

**Comment by uNetworkingAB** [comment]
Well, I have submitted a PR to TechEmpower that doubles the plaintext perf. now. That's all I can do about it

**Comment by uasan** [comment]
A good point about the server’s suitability for real production, one of the criteria for such suitability is the server’s ability to work effectively with static files, I don’t know of a single serious web server that cannot send and send files, the same Njinx has become popular thanks to this, among other things, I’m writing this not for trolling, like feedback from a production solutions developer.

**Comment by uNetworkingAB** [comment]
These DeclarativeResponses (or whatever to call them) can be used for a lot of things: all things that are public and time-oriented like:

* Responding with the current price of gold (or any asset) - this covers the whole public part of trading APIs
* Responding with the current time
* Responding with the current game state or match state

How? Well they can be seen as just constant strings, and you can attach new ones every second or whatever update granularity you need. So if you have a setInterval timer of 10 seconds, and have it register new constant responses, data will be up to date whenever someone requests it.

So for delivering the price of asset XX, you can get 2x the performance without writing the internal data fetching in C++. So you can still have slow moving script that fetches the data, and then have fast getters over HTTP still.

I know, it's not rocket science. You can essentially reduce it to "can I attach a constant string to a URL instead of a function" - yes you can.

Same goes for files - serving files could be simple.

You could dig more into this and make it more complex. You could use this new interface as a way to implement the MessageBatch I talked about, where small requests are copied and batched to minimize calling into JS. But that's kind of pushing it beyond what I was planning for now.

First step is to see if/when TechEmpower people respond to/merge the change. I can't see them deny it, given that NGINX has the same exact approach (no code, just static config).

You could also, simply remove all of this, and only allow constant strings instead of functions. That functionality still solves the issue of serving the price of gold and other assets, quickly.

**Comment by uNetworkingAB** [comment]
Lol it's basically a caching proxy. But not a proxy. Well I tried.
