### ISSUE TITLE
[Feature Request] Deno

### ISSUE THREAD

**Issue by Malix-off** [uNetworking/uWebSockets.js#1091]
As this project releases binary for node, and bun ships uWS through their stdlib under-the-hood, deno is left without an option to use uWS (or I missed something ?)

It would be nice if uWS could be usable in deno

**Comment by uNetworkingAB** [comment]
Deno is not compatible with Node.js in terms of native addons, or internal native components like libuv. And keep in mind uWS.js is from 2015/2016 back when Node.js was immensely popular and there were no alternatives.

**Comment by Malix-off** [comment]
Ohkay

I asked them if they planned to implement uWebSocket under the hood : https://github.com/denoland/deno/discussions/25003

**Comment by SerJaimeLannister** [comment]
Though deno supports websockets , there are many node based projects which actually use uwebsockets.js and now deno does support  node backwards compatibility (even more so than bun which uses uwebsockets.js   )

I wish to reopen this please.

**Comment by josephrocca** [comment]
Not sure if this is relevant but as of a few days ago "Deno's fully featured, zero-overhead FFI is stable":

* https://x.com/deno_land/status/1884663018409386436
* https://denonomicon.deno.dev/basics

```js
// Open a native library
const lib = Deno.dlopen(
  "./libfoo.so",
  {
    // Declare symbols
    method: {
      parameters: ["u8"],
      result: "pointer",
    },
  },
);

// Use symbols
const resultPointer = lib.symbols.method(35);
```

**Comment by uNetworkingAB** [comment]
Again, uWS for Node.js is from 2016. Back then, Deno & Bun did not exist
and "websockets/ws" for Node.js was much slower & even more bloated.
Node.js was at v0.12 and most people used Express.js. Then, uWS came with
massively boosted performance.

Today, there is no necessity for uWS in the JavaScript ecosystem since Bun
already uses it and Deno has its own very fast implementation. There is no
incentive or reason to try and shoehorn uWS into Deno, esp. since Deno is
fundamentally incompatible.



Den lör 1 feb. 2025 kl 16:47 skrev josephrocca ***@***.***>:
