### ISSUE TITLE
Benchmark Testing in Single-Thread, Multi-Thread, and Cluster Modes

### ISSUE THREAD

**Issue by andrehrferreira** [uNetworking/uWebSockets.js#1097]
We conducted extensive benchmarking tests across three modes: single-thread, multi-thread, and cluster. The goal was to evaluate the performance of different frameworks under various configurations.

Results Overview:
In single-thread mode, uWebSockets.js (uws) stood out significantly, delivering the highest performance in terms of requests per second and low latency.

However, when tested in cluster mode, uWebSockets.js exhibited performance that was significantly lower compared to other frameworks. Despite excelling in single-thread scenarios, it struggled to scale efficiently in a clustered environment.
The performance differences in multi-thread mode were more balanced, though uWebSockets.js still maintained an edge in certain scenarios.

These findings suggest that while uWebSockets.js is highly optimized for single-threaded applications, its cluster-mode performance could be improved to better handle distributed workloads.

| (index) |     Framework      | Requests/sec | Transfer/sec |  Latency   | Total Requests | Transfer Total | Latency Stdev | Latency Max |
|---------|--------------------|--------------|--------------|------------|----------------|----------------|---------------|-------------|
|    0    | cluster_fastify     |  138457.36   |   23.24MB    |  15.58ms   |    1388733     |    233.09MB    |   58.10ms     |  842.11ms   |
|    1    | cluster_http        |  137054.68   |   23.27MB    |  14.56ms   |    1376920     |    233.74MB    |   52.84ms     |  802.10ms   |
|    2    | cluster_koa         |  122922.41   |   20.51MB    |  14.97ms   |    1234474     |    206.03MB    |   52.39ms     |  823.15ms   |
|    3    | cluster_hapi        |   94445.64   |   19.91MB    |  23.66ms   |     949082     |    200.03MB    |   83.97ms     |    1.10s    |
|    4    | cluster_restify     |   93398.96   |   16.48MB    |  22.78ms   |     937893     |    165.47MB    |   79.86ms     |    1.09s    |
|    5    | cluster_express     |   43577.99   |    9.89MB    |  60.64ms   |     437738     |     99.36MB    |  190.66ms     |    2.00s    |
|    6    | single_uws          |   37081.93   |    3.71MB    |  27.45ms   |     372355     |     37.29MB    |    3.06ms     |  76.40ms    |
|    7    | cluster_uws         |   35629.39   |    3.57MB    |  28.57ms   |     357699     |     35.82MB    |    1.82ms     |  95.33ms    |
|    8    | single_http         |   24159.04   |    4.10MB    |  42.09ms   |     242998     |     41.25MB    |    7.12ms     |  235.08ms   |
|    9    | single_fastify      |   23794.91   |    3.99MB    |  43.18ms   |     239197     |     40.15MB    |   11.90ms     |  343.66ms   |
|   10    | single_koa          |   20263.96   |    3.38MB    |  50.25ms   |     204371     |     34.11MB    |   17.65ms     |  294.61ms   |
|   11    | single_hapi         |   14163.93   |    2.99MB    |  71.82ms   |     142853     |     30.11MB    |   16.06ms     |  410.62ms   |
|   12    | single_restify      |   14036.58   |    2.48MB    |  72.46ms   |     141118     |     24.90MB    |   13.49ms     |  527.51ms   |
|   13    | single_express      |   6830.47    |    1.55MB    | 147.89ms   |      68993     |     15.66MB    |   29.75ms     |  626.75ms   |

The code used to perform the thread test was available in the samples

```javascript
'use strict';

const { Worker, isMainThread } = require('worker_threads');
const uWS = require('uWebSockets.js');
const numCPUs = 6;
const port = 3000;

if (isMainThread) {
	for (let i = 0; i < numCPUs; i++) 
    	new Worker(__filename);
} else {
	const app = uWS.App().get('/*', (res, req) => {
		res.end('Hello World!');
	}).listen(port, (token) => {});
}
```

**Comment by porsager** [comment]
No info about what this is run on, but color me surprised if this isn't MacOS?

**Comment by uNetworkingAB** [comment]
uWS is not optimized for single core. It's optimized for whatever number of cores you have.

What client? Where did it run?

**Comment by uNetworkingAB** [comment]
Cluster doesn't work on macOS. That's why you get no improvement. Benchmark on Linux

**Comment by uNetworkingAB** [comment]
Expect perf. to be linear with number of cores and debug your benchmark accordingly.

**Comment by uNetworkingAB** [comment]
Closing invalid issue. uWS is 12x faster than Fastify on 4-core cluster. It's a botched benchmark.

https://medium.com/@unetworkingab/serving-100k-requests-second-from-a-fanless-raspberry-pi-4-over-ethernet-fdd2c2e05a1e

**Comment by andrehrferreira** [comment]
Hi @uNetworkingAB 

From what I saw in your post, your test was done directly on the uWebsocket version in C++, the tests I performed were on the Javascript version, because honestly comparing a C++ HTTP server really doesn't make sense, my question was not in terms of single thread performance, which uWebsocket actually outperformed all the others, my point was in terms of the cluster / multi thread of node.js, the only possible way today to "solve" this problem in my point of view would be to use a load balance in nginx for example, exposing the application on different ports, and the reason for opening the question was because in the project samples there is a thread worker implementation that apparently is not working.

**Comment by porsager** [comment]
Running benchmarks on WSL on Windows and expecting any kind of sensible output is not conducting extensive benchmarking. I just did an equally bad thing and ran you benchmark on my mac in a parallels ubuntu vm.. 

Now just looking at your results it's obvious something is wrong since you get the same result with multiple workers for uws as with a single worker.

Now don't take these numbers as showing anything meaningful other than uws being fast and the rest being slow... If you tested on a proper setup with a properly configured linux the difference would be even bigger. Oh - there's also this you should check out : https://github.com/uNetworking/uWebSockets.js/issues/1078 

### Single worker
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/03ceeb0a-2883-4e10-a411-6ee5f6f692f4">

### 6 workers
<img width="1164" alt="image" src="https://github.com/user-attachments/assets/3d59490a-552a-4385-a54a-753062e50158">

**Comment by andrehrferreira** [comment]
Hi @porsager 

I just used the example provided in the samples and tried to run it, but it simply didn't work. It was mentioned that it only runs in a Linux environment, and yes, I executed it on Ubuntu. I'm not questioning the results or complaining, just stating that the code provided in the samples isn't working for some reason.

Regarding the topic of uWebSocket being banned from TechEmpower, I’d like to provide honest feedback. I’ve been in the industry for 22 years and have contributed to several open-source repositories. This is the first time I’ve ever felt so unwelcome by a project maintainer. It gives the impression that the ego of the team is so inflated that anyone who apparently "criticizes" the project is immediately dismissed. That was not my intention. If I didn’t like the project, I wouldn’t have wasted my time submitting a PR or leaving a comment here.

Unfortunately, this kind of attitude completely discourages me from considering the project for any future use. I have no confidence that in the case of issues, the developers would be willing to listen and fix them as any respectable project would. That said, congratulations on the project and I wish you all much success.

**Comment by porsager** [comment]
Think of the time you expect others to waste, and then reconsider what you just wrote. Did anybody ask for your PR? Why didn't you ask first? Did you consider the time burden you put on a maintainer when submitting benchmark numbers that are flawed? Claims that will then require effort to explain / disprove? Not because of ego, but because others shouldn't be misguided thinking these numbers are correct? It is quite the entitlement to come and claim high moral ground when you, not even once, in any of your original posts entertained the idea, that something might be wrong with your benchmarks. That you didn't spend the time to investigate the extensive benchmarks that had already been made. 

And even then - benchmarks like these are worthless. Benchmark for your use case. All the performance you gain by using uws will probably go down the drain when you put your code behind it. That's why you benchmark once you've got actual real world use cases.

I have no affiliation with uws other than being a very happy user, but I know Alex is wiser than me not spending time on things like these. I just didn't want to let you leave empty handed, and hopefully give a little back considering the fact that he made all this freely available. I might also have a slight hope on behalf of other maintainers that you'd think twice about the way you approach these things.

**Comment by andrehrferreira** [comment]
@porsager 

The test I ran used the official code provided in the repository. So, the tests work for every other library except uWebSocket? That doesn't make sense to me. In my understanding, there could be some limitation due to the fact that it's a C++ implementation compared to native ones. For example, using asynchronous functions might cause errors in uWebSocket.

Another important point: when you position yourself as the maintainer of an open-source project, you should be prepared to answer all kinds of questions. Otherwise, you should consider leaving open source and selling your solution as a paid consultancy. Opening an open-source project and then acting impatiently with someone submitting a PR, saying something like, "Did anyone ask for your PR?", is counterproductive.

Let me tell you a truth: the project might have all the technical quality in the world, but it will never become big. And do you know why? Because projects don't grow just from beautiful code, but from people who believe in them and trust the maintainers. Clearly, that's not the case here. It seems I'm not the only one thinking this way, since something similar happened with TechEmpower, right?

In the end, your project risks ending up like Deno: created by a genius, but no one trusts it. In the long run, it will die like many others. Meanwhile, technically inferior projects like Express will continue to thrive. Why? Because over there, people are respected, and there is a true sense of community.

**Comment by uNetworkingAB** [comment]
>  I’ve been in the industry for 22 years and have contributed to several open-source repositories. This is the first time I’ve ever felt so unwelcome by a project maintainer.

Wait what? You feel 22-year all-time-high levels of unwelcome because I closed your issue under "invalid"? But your issue, objectively IS invalid. As shown by the linked blog, also you can see it in TechEmpower which uses Node.js cluster feature on a multi-core CPU. I also personally tested this just now, and I have personally tested this many times.

If the statement you make - that uWS sees 0% gain from running multi-core, then how on earth can it score top 3 in TechEmpower where the CPU is like, 64-core Intel Gold or whatever. It logically does not hold for 2 seconds of critical thinking.

This is why I closed the issue. Not because of unwelcomeness or any other subjective reason.

**Comment by andrehrferreira** [comment]
I'm not questioning the closing of the topic, but rather the answer given by @porsager

**Comment by uNetworkingAB** [comment]
Can we just revert back to basic logical thinking:

1. We know from very recent work that uWS.js has top-3 result in TechEmpower's plaintext which runs on 28-threaded CPUs (which could even be outdated specs by now).

This bullet point alone logically disproves your original statement (which was that uWS.js has 0% gain in multi-core CPUs)

Therefore, this thread is pointless

**Comment by andrehrferreira** [comment]
I believe you in this statement, what I want to understand is why the sample worker thread is not working to have this result, this is the reason for opening the question

**Comment by uNetworkingAB** [comment]
Running the verbatim WorkerThreads.js example with Node.js 21 just now, showing 200% CPU-time usage for the two threads in use by the example.

![Screenshot 2024-08-23 013203](https://github.com/user-attachments/assets/98039147-60be-4647-a2e2-4bbdbec9067c)

**Comment by e3dio** [comment]
This guy comes on here, posts invalid benchmarks, insults the project and maintainer, then expects everyone else to figure out why his WSL test isn't working, he has clearly not done any basic troubleshooting steps himself, what a jerk

**Comment by uNetworkingAB** [comment]
Yes I am actually fascinated by this mindset.

**Comment by uNetworkingAB** [comment]
> when you position yourself as the maintainer of an open-source project, you should be prepared to answer all kinds of questions. Otherwise, you should consider leaving open source and selling your solution as a paid consultancy. Opening an open-source project and then acting impatiently with someone submitting a PR, saying something like, "Did anyone ask for your PR?", is counterproductive.

We are not hiring for a Chief Strategy Officer currently. Thank you for your letter.

**Comment by uNetworkingAB** [comment]
I ran your verbatim snippet you posted against wrk. I get close to linear gain with 2 CPUs compared to 1 CPU. I tested both worker threads and cluster. Both work and both give the same speedup.

If you added logging in the listener callback you would catch any listening issues, but you never did so we can't know. But most likely all but 1 listen failed due to _whatever system settings_ you have.

**Comment by uNetworkingAB** [comment]
So essentially we can conclude that, had you done proper error checking and actually measured CPU-time usage or simply done a few seconds of critical thinking, you had caught the fact your results are entirely botched and make no sense.

**Comment by uNetworkingAB** [comment]
@andrehrferreira Are you interested in testing a new approach that will fix the macOS issue, and potentially make it more strictly balanced? I will make a new example with this approach, if you want to try it.

**Comment by uNetworkingAB** [comment]
WorkerThreads.js example should now work on macOS and on Linux will guarantee round robin distribution. It's not released yet but can be tested from latest binaries.
