### ISSUE TITLE
Support of Node 23.х (module version 131)

### ISSUE THREAD

**Issue by aleksraiden** [uNetworking/uWebSockets.js#1116]
In a new version of NodeJS modules have a version 131 (see: https://github.com/nodejs/node/commit/17a17164d6) to adopt a new V8 version.

Please, add support of this platform

**Comment by uNetworkingAB** [comment]
Yes it will come soon

**Comment by Maclay74** [comment]
I think that even 22 isn't supported currently:
```
Error: This version of uWS.js supports only Node.js versions 18, 20, 21 and 22 on (glibc) Linux, macOS and Windows, on Tier 1 platforms 
Error: Cannot find module './uws_win32_x64_127.node'
```

```bash
node -v
v22.11.0
```

**Comment by uNetworkingAB** [comment]
You need to update uWS

**Comment by maxpain** [comment]
any updates?

**Comment by uNetworkingAB** [comment]
You can install latest nightly builds

npm install uNetworking/uWebSockets.js#binaries

**Comment by uNetworkingAB** [comment]
This thing is failing on Windows Node 23

// gcc 10 defines __cplusplus to "an unspecified value strictly larger than
// 201703L" for its experimental -std=gnu++2a config.
// TODO(leszeks): Change to `__cplusplus <= 202002L` once we only support
// compilers with full C++20 support.
#if __cplusplus <= 201703L
#error "C++20 or later required."
#endif

**Comment by uNetworkingAB** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170

**Comment by ZouJiu1** [comment]
**the reason is the version of node is too high, you should downgrade the version to v20

brew install node@20

v22 is too higher

[https://zoujiu.com.cn](https://zoujiu.com.cn/#/csdn/markdown_detail/*?plan=/home/admin/vue-project/article/csdn_spider_selenium/article/2024-12-17_%E7%A9%BA%E6%A0%BC_21_50_10_Macos%E4%B8%8Anpm_%E7%A9%BA%E6%A0%BC_%E7%BC%96%E8%AF%91_%E7%A9%BA%E6%A0%BC_vscode%E6%8A%A5%E9%94%99%E4%BA%86_%E9%80%97%E5%8F%B7_%E5%85%B7%E4%BD%93%E7%9A%84%E6%98%AF%E7%89%88%E6%9C%AC%E5%A4%AA%E9%AB%98%E4%BA%86_%E9%80%97%E5%8F%B7_node-gyp_%E7%A9%BA%E6%A0%BC_C%2B%2B20_%E7%A9%BA%E6%A0%BC_or_%E7%A9%BA%E6%A0%BC_later_%E7%A9%BA%E6%A0%BC_required_%E7%A9%BA%E6%A0%BC_/2024-12-17_21_50_10_markdown.md)

[https://nodejs.org/zh-cn/download/package-manager](https://nodejs.org/zh-cn/download/package-manager)**
