### ISSUE TITLE
its possible to use it as HttpClient ?

### ISSUE THREAD

**Issue by Biswajit96** [uNetworking/uWebSockets.js#1145]
its possible to make a custom http client use uWebSockets.js? for call json apis etc.

**Comment by the-lstv** [comment]
uWebSockets is a server not a client.

**Comment by uNetworkingAB** [comment]
Only server, no client

Den tis 17 dec. 2024 17:52LSTV ***@***.***> skrev:

**Comment by Biswajit96** [comment]
> No. uWebSockets is a server, not a client.
> 
> Adding a client is not planned (as far as I'm aware).
> 
> I also don't understand why do some people want this... there isn't really a good reason for it? How would it be useful

The fact is, there are only a few reliable high-performance HTTP clients in the market. One of them starts with "Un***i." When you ask advanced AI for the best high-performance HTTP client capable of handling 10k QPS or more, it consistently ranks **uWS** at the top.

**Comment by the-lstv** [comment]
> > No. uWebSockets is a server, not a client.
> > Adding a client is not planned (as far as I'm aware).
> > I also don't understand why do some people want this... there isn't really a good reason for it? How would it be useful
> 
> The fact is, there are only a few reliable high-performance HTTP clients in the market. One of them starts with "Un***i." When you ask advanced AI for the best high-performance HTTP client capable of handling 10k QPS or more, it consistently ranks **uWS** at the top.

Sure, well if you are using AI then maybe anything's possible, I guess.

GPT-4o just confidently hallucinated an entire `uWS.HTTPClient` API along with full description and reasoning on why it isn't documented, and was pretty confident that it currently exists.

It was also pretty confident that uWebSockets fully support HTTP/2, among other things. So..

Just because "advanced AI" outputs something, it doesn't make that it in any way credible or even remotely guaranteed to be valid.
AI isn't magic, and it doesn't know or think anything either. It's just a fancy tool that predicts text, taken from other text sources, and alters it with some RNG.


uWebSockets currently do not expose a HTTP client. It may exist in the future but it doesn't exist now.

And I don't see an issue with the current HTTP client implementations for Node.
I don't see how a uWebSockets client would be that much useful at this time.

Sure, maybe in the future it could be cool.

**Comment by uNetworkingAB** [comment]
Lol. Be kind to chatgpt 😭

Den tis 17 dec. 2024 22:36LSTV ***@***.***> skrev:
