### ISSUE TITLE
What is the proper way to deal with backpressure?

### ISSUE THREAD

**Issue by ohenepee** [uNetworking/uWebSockets.js#169]
There seem to be a lot of talk about backpressure but no clear ways to handle it... I just found out that using the `ws` argument in `drain` always returns false for `ws.send`.

So what is one actually supposed to do in the drain handler? You check for getBufferedAmount, if its 0 (zero), then what?

I've piled up data from the `message` handler when false is returned by `ws.send` I need to send to the client, how do I resume sending it since I am no more in the `message` handler?

**Comment by ohenepee** [comment]
I have taken 2 good hours to search GitHub code using uWebSockets (including even the C++ project itself)

1. There's no productive use of the `drain` event in the docs or anywhere.
2. Everyone (I mean literally everyone on GitHub) using this particular library don't know the heck to do with the `drain` so they're just logging `getBufferedAmount()` just as in the examples (personally I think this is dumb). What makes it dumber is the fact that no one has EVER ask this in the issues.

Still don't know whether to bombard (buffer) the client's socket with all the messages that need to be sent or wait for something imaginary to pop up somewhere 🤣

**Comment by alexhultman** [comment]
You obviously found all the involved parts already - `drain`, `send` and `getBufferedAmount`. Read their documentation.

There are plenty of docs and manuals for this. More than enough to solve this issue. Whatever you do with backpressure is out of scope of this library - it doesn't care what you do with it - you can choose to ignore it (like most Node.js projects do) or come up with some stable, streaming solution.

**Comment by alexhultman** [comment]
> I just found out that using the ws argument in drain always returns false for ws.send

This is incorrect. Read the docs.

**Comment by ohenepee** [comment]
Alex... I've read the docs a long time ago over and over again, but in my test `getBufferedAmount()` returns `0` which is green light, yet `ws.send` returns `false`.

Unless perhaps there's a different doc you're referring to. `ws.send` works perfectly in the `message`, but I can't say the same for the `drain`.

**Comment by ohenepee** [comment]
I think the title I used is a bit misleading, I wasn't really looking for how to deal with backpressure as that is straightforward. You can easily tell I had it figured out from the issue I raised.

However the fact that I couldn't get `ws.send` to return `true` in `drain` is what brought me to the belief that perhaps there was a different way backpressure is to be handled with this library since you hate following the supposed "standards" or inefficient conventions.

**Comment by marcj** [comment]
Of course `ws.send()` returns false in `drain`. It's the very reason why `drain` is called in the first place. When `drain` is called it means you need to take actions because the network is too busy. Sending even more data at the exact moment when you get notified about that event is not something that helps. So what you need to do is simple when you get `drain`: Schedule all `send` calls until getBufferedAmount() is back on a healthy level. This means: Don't send any more data and just wait. How you do that is up to you and your use-cases.

**Comment by Ahmdrza** [comment]
@marcj thanks for detailed explanation. In real-time chat, one can't wait for messages to send only if getBufferedAmount() is back on healthy level as chats are supposed to be live and suppose if there's a wait of even half a min, which is too much, users will not like our application. How is this issue handled?

**Comment by marcj** [comment]
@Ahmdrza I tried to implement a way to handle the drain events of uWebSockets but ended up replacing uWebSockets with the more stable `ws` package. I never was able to implement a working and fast solution that handles those drain events, although I've spent a fair amount of time in it.

So to answer the question:
> What is the proper way to deal with backpressure?

There is no proper way to deal with this in uWebSockets. The author of this library has obviously no interest in explaining it and opposing to his argument there is no docs anywhere available that explains how to implement a way to deal with back-pressure, so I recommend to not touch this library when you have back-pressure issues. I also pointed out a misbehavior in the underlying library (https://github.com/uNetworking/uWebSockets/issues/1000) which made it impossible to deal with back-pressure at all (since send() returns false indicating message not being sent so back-pressure occurred, but in fact it was sent), but again the author was not willing to help. You should better just use the [`ws` package](https://www.npmjs.com/package/ws), which solves this whole mess for me.

This whole uncooperative play from the author indicates that back-pressure is not correctly handled in this library and thus should not be touched.

**Comment by alexhultman** [comment]
@marcj That sure took a fast turn for the worse. What exactly is it you don't understand about the docs? We already have people successfully using this feature, so claiming it's entirely broken is quite ignorant.

> Sends a message. Make sure to check getBufferedAmount() before sending. Returns true for success, false for built up backpressure that will drain when time is given.

This is quite obvious. Returning false does not mean nothing was sent, it means, just like the docs say that backpressure was built up. You posted an issue complaining about how false is returned even though data was sent - these are not in conflict with each other like you can read in above text. You are making assumptions that are not true, then you blame everything on me for not getting it working.

That's quite childish behavior, esp. when you have commercial support if you really want help. But of course you require everything to be handed for free, like a true communist, then complain for the lack of good free support. It's really shameful behavior if you ask me. I'm not going to spend my time personally tending to every free user's needs. I can only fix and document things which many people have issues with.

The backpressure support is pretty much identical to the one you already have standardized in the browser. You have the exact same functions there - ws.send and ws.bufferedAmount so your logic checking those are exactly the same - we also provide an handler for drain to further help you.

But of course I'm a horrible person for not personally consulting your needs for free. Esp, when I know people to successfully use this feature.

Sure by all means, if ws solves your problems better than µWS then of course you should use that software instead - that kind of explains itself. If you have no reason to use µWS then don't. Nobody is bending your arm here - you have free will.
