### ISSUE TITLE
npm WARN deprecated uws@9.148.0: stop using this version

### ISSUE THREAD

**Issue by niahmiah** [uNetworking/uWebSockets.js#2]
Where are new builds for node published?

**Comment by alexhultman** [comment]
Upcoming. Probably they will be made as loosely flying tags or in a separate branch in this repo. That makes it possible, what I understand, to install with NPM while not relying on the NPM registry.

To clarify: "deprecated" does not mean "this code contains gonorrhea, stop using it immediately or your family dies". It just means... stop using it.. whenever you are ready to. It will be replaced with new releases when said releases happen to be ready.

**Comment by niahmiah** [comment]
Thanks for clarifying. Closing.

**Comment by iatsiuk** [comment]
Hi! I am just curious to know what's wrong with NPM registry?

**Comment by alexhultman** [comment]
It is not as liberal as I would like to. I don't care for third parties who enforce decisions in areas where they should have no say. NPM should host things and let the market control itself. Also, their terms of use is an American nightmare:

Unlimited, eternal, indemnification liabilities + inability to ever delete, modify or republish = unacceptable.

**Comment by davalapar** [comment]
Watching this repo for now!

I've read multiple threads about what happened and really wish this gets sorted out in your own way.

Your work has really outpaced `ws` and other websocket libraries in terms of minimalism and performance, and some developers has really overlooked your rights as the author by prioritizing their convenience and community idealisms first.

Please take your time man, respect!

**Comment by SkeLLLa** [comment]
Just an idea for new builds. Npm (since 5.6.X version) and yarn work fine with git tags. So it will be even possible to use semver, like `https://github.com/uNetworking/uWebSockets-node#semver:^1.2.3`.

Also as an alternative approach you may also consider launching own npm with [verdaccio](https://github.com/verdaccio/verdaccio) or similar soft, where you will be not affected by weird npm limitations. And publish publish modules under some namespace like `@uNetworking`, so it will be easy for devs to add it in their own projects.

**Comment by alexhultman** [comment]
Yes git tags will probably be used. Like I mentioned in the first comment.

**Comment by Andrews54757** [comment]
@alexhultman I understand that it is due to NPM's strange rules that you decided to take your package off, but why did you set it to an empty package? Lots of people's projects broke, and no one seems to know why yet. Lol, it took me a couple of hours to figure out why my [SimpleSockets](https://github.com/AJS-development/SimpleSockets) library returned an error: `cannot find module 'uws'` for a game im developing.

:( :( :(

**Comment by Andrews54757** [comment]
@SuperOP535 Yeah, I know. But it took me a long time to figure that out. Empty packages are usually the rarity, and an unsupported environment is more likely the cause. Thus I spent lots of time figuring out what was wrong with my computer.

**Comment by sergioivan154** [comment]
> @Andrews54757 just put this in your package.json and install `"uws": "10.148.1",`

Can you share your package.json
?

**Comment by SuperOP535** [comment]
@sergioivan154 Just put it in your `"dependencies": { ... }` and if you put it in the last row remove the comma if you don't have a package.json running npm init will do the work for you

**Comment by GeekMode** [comment]
> 
> 
> > @Andrews54757 just put this in your package.json and install `"uws": "10.148.1",`
> 
> Can you share your package.json
> ?

`npm install uws@10.148.1`
or
`yarn add uws@10.148.1`
