### ISSUE TITLE
[Info] deprecated uws version

### ISSUE THREAD

**Issue by edreal** [uNetworking/uWebSockets.js#207]
I've been using the older deprecated uws version which is good as well but it doesnt have support for newer node versions. Does this 16.0.0 work in Node.js v12?

Do you have any idea about performance differences between this and the older one?

Also in most of the examples there is the .any which returns 'Nothing to see here', is it necessary to have even if I dont want to serve normal http requests?

Thanks!

**Comment by alexhultman** [comment]
> the older deprecated uws version which is good as well

Yeah if you feel like running on a heap of security vulnerabilities...

Technically all 15 major versions made before version 16 are "deprecated", since I do not have resources to keep multiple branches supported simultaneously. Deprecation happens to every non-latest release, continuously.

This applies to every prior release; it is unsupported and should not be used. Now, some people believe that clicking the "fork" button, changing the project name and removing the deprecation warnings is enough to "fix" old releases for perpetual use but obviously this is just fooling yourself as these "forks" are left entirely broken, "maintained" by people who have no idea what they are doing. Putting a new logo on broken code does not fix it. It's simply re-branding my old garbage code I threw out long ago.

For instance, https://www.npmjs.com/package/sc-uws is basically a republish of old code with security vulnerabilities. What's sad is that people believe this to be "maintained" code and you can see this package is actually growing in terms of downloads which is just horrible. It's cherry-picking the good and mentally blocking the bad. I wrote the code, so I know exactly what I'm talking about. 

Why people care to swap from "uws" to "sc-uws" is mindblowing as they are exactly the same deprecated unsupported code. It's nothing more than gut-feeling & human psychology. It literally makes no difference.

New releases starting from v16.x.x have an entirely different focus on security, working with Google's fuzzing service to track and fix vulnerabilities as soon as they are found.

Performance is on a completely different level from v16.x.x with very performant pub/sub and significantly faster messaging from 15.x.x. One big reason for the new API in 15.x.x was to allow a much more efficient implementation, completely bypassing Node.js's HTTP support.

All new Node.js versions are supported with new versions of uWebSockets.js, lagging behind a few weeks.

But hey, whatever floats your boat.
