### ISSUE TITLE
This version of µWS is not compatible with your Node.js build

### ISSUE THREAD

**Issue by OmgImAlexis** [uNetworking/uWebSockets.js#289]
```shell
npm install uNetworking/uWebSockets.js#v17.3.0
proxy@0.0.1 /usr/local/bin/proxy
├── UNMET PEER DEPENDENCY bufferutil@^4.0.1
├── UNMET PEER DEPENDENCY utf-8-validate@^5.0.2
└── uWebSockets.js@17.3.0  extraneous (git://github.com/unetworking/uWebSockets.js.git#f54d0b45d1d9924d2562fd8f6f59cbca2bcbcc2c)

npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN proxy@0.0.1 No repository field.
```

This type of warning should be thrown on install not when running the application.
```ts
throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
```

**Comment by alexhultman-2fa** [comment]
This is an opinion. Do you have any technical problem with the install?

**Comment by OmgImAlexis** [comment]
You've seem to not want to deal with what you deem as "frivolous" issues, this could help with that.

The technical issue I have is how do I know which version to use? I'm using the latest LTS version of node. I've tried the version listed on in the readme and it doesn't install.

**Comment by alexhultman** [comment]
Front page:

> Install with npm install uNetworking/uWebSockets.js#v17.3.0 or any such release. No compiler needed.

This works for most people, if it doesn't work for you (running some weird Linux dist, running inofficial builds of Node.js, etc) then it's up to you. I don't provide any help or support regarding this. Project is provided as-is.

**Comment by OmgImAlexis** [comment]
I’m running the latest version of node. This also happened on my Mac. Don’t really get how the latest LTS on macOS is that far off from what most users would be running?

Am I missing something here?

**Comment by xbpiao** [comment]
why not use node-gyp compile?
Support all platforms

**Comment by alexhultman** [comment]
This is a very frequently asked question and there is already an answer pinned.

**Comment by StefansArya** [comment]
Maybe because some of them are using Electron or NW.js that have different [ABI version](https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json) for the Node.js.

The possible solution is using Electron version <4.0.4 because it's using module v64. But my current Electron version is v8.2.3 (node module v76), so I don't think I should downgrade that much. My another Electron with v7.1.7 is using module v75, I have no choice then..

Another possible solution is separate the node script that using uWebSocket, and run it when electron app is going to start (in `main.js`).
```js
require('child_process').spawn('node', ['./uServer.js'], {
    stdio: 'inherit'
});
```

It's now working, but for the consequence the Electron app also need to connect to the server as a client to communicate. And on production I may need to bring compatible `node.exe` if the user never installed NodeJS on the computer. I would miss feature like importing module right into the window app:
```js
var server = require('./uServer.js');
server.on('new-user', function(data){
     $('#userlist').text('connected user: '+data.counter);
});
```

But most importantly, now I can start the server 😄

**Comment by alexhultman** [comment]
This project is a Node.js project; it is not an Election project and for the same reasons it also has no client support. Because Electron apps are clients, generally speaking.

This is a back end server project for those who need a more performant and reliable alternative, it is not intended to fit everywhere just for the sake of being popular.
