### ISSUE TITLE
Unnecessary text

### ISSUE THREAD

**Issue by sirganya** [uNetworking/uWebSockets.js#332]
Even though you owe us nothing, have shared your talent with us and own this work I think you went too far with the issue from zdm that you deleted. You had made your point and there was no need to add an extra message that was abusive. You may feel justified in lashing out at people because they are not as talented as you but I would like to say to you now, categorically, you are not. I think you should remember back to the people who helped you learn. I'm sure you were never on the receiving end of abuse for an oversight when you were a newbie. There is no purpose to it. I used to think you were caustically funny but you crossed a line for me last week. You have created a community around your work and you don't have to answer us anymore than you already do or change your hard-ass tone (of which I have been on the receiving end of) but you're not justified  in going to the extra effort of abusive ranting. Words matter as you pointed out in your screed. Feel free to delete this when/if you read it. I have no wish to start a debate.

**Comment by hst-m** [comment]
Github needs to get that Discussions feature going, pretty sure that will solve the problem, instead of creating issue for every random question which are intended for bug reports etc, I post some dumb stuff from time to time, but check out this Discussion feature looks pretty cool https://github.com/vercel/next.js/discussions

**Comment by alexhultman** [comment]
I'm about 110% categorically justified in expressing anything between heaven and earth, thank you very much.

We've had extensive freedom of expression laws established in Sweden since before USA was even an idea. Of course, if you want to forcefully limit the written word to only a tiny safe space bubble where no criticism may exist you can always go to China or North Korea. But it won't favor you, anyways.

I could have been more friendly in this particular case, sure, but analphabetic stupidity has no place in this repo and it makes me angry. We have a lowest bar and if you fall below it you can go do finger painting somewhere else.
