### ISSUE TITLE
node version http/ws performance

### ISSUE THREAD

**Issue by hst-m** [uNetworking/uWebSockets.js#341]
ran some benchmarks with [nvm](https://github.com/nvm-sh/nvm#node-version-manager---) and it does appear there is correlation with each new node version and decreasing performance of uWS.js http (requests per second)

![image](https://user-images.githubusercontent.com/65402951/86506880-666f6600-bd88-11ea-9f6b-66b982573273.png)

**Comment by alexhultman** [comment]
Absolutely. That's what I've been saying for years. The only limit uWS has is `node::MakeCallback` and they manage to tamper with that every release, to our disadvantage. I'm absolutely not claiming conspiracy, though. They don't even know or care about this project and the explanation isn't ill intent but rather incompetence.

They never benchmark their changes and if they do, they allow small drops of loss by every release, because they have no discipline or leadership to say no. Many drops make an ocean over time.

If you plot the same graph with vanilla V8 you'll see a flat line, this because there's a huge massive difference in competence and leadership between Googlers and amateurs.

Nodejs accepts anyone to jump in and make changes, the one making the most internal C++ changes (I cannot mention this person because then I would probably commit hate speech in some absurd way) have even said that he/she have no history with C++ and is just learning by doing. Well that's called being an amateur.

Alright, again nothing I can do about this

**Comment by hst-m** [comment]
Websocket echos per second also showing the same thing. What is going on over there they just keep adding more code
and it is slowing stuff down?


![image](https://user-images.githubusercontent.com/65402951/86503815-8f7eff00-bd66-11ea-9432-ce3c04520300.png)

**Comment by hst-m** [comment]
Must be something they can do to fix it, that's a 33% performance drop for sockets and 25% drop for http from node v10 and this library only hooks into theirs minimally so maybe have someone over there look into it, get it back up to 100%

**Comment by alexhultman** [comment]
If you look at the history of (C++) uWS you see that the trend went the other way:

v0.14.0:
Running benchmark now...
Msg/sec: 199302.500000
Msg/sec: 200806.000000
Msg/sec: 198921.750000
Msg/sec: 198346.000000

v18.9.0:
Running benchmark now...
Msg/sec: 245320.500000
Msg/sec: 246637.500000
Msg/sec: 247706.000000
Msg/sec: 246724.750000

This is for WebSockets but the same can be seen in Http, even though v18 has a complete router on top.

**Comment by alexhultman** [comment]
I wrote a benchmark that just does node::MakeCallback a million times in different Node.js versions.

* Node.js 13.8.0 does it in 273ms
* Node.js 13.9.0 does it in 622ms
* Node.js 14.5.0 does it in about 600ms, but sometimes 800ms

And this benchmark does nothing at all besides calling node::MakeCallback - the single one function we use.

**Comment by alexhultman** [comment]
@BridgeAR You had some questions regrading this a while back - what's your take on this?

**Comment by alexhultman** [comment]
![chart](https://user-images.githubusercontent.com/3397140/86506040-a99ef880-bdcb-11ea-9758-6c8fd340ade0.png)

For the visual learners

**Comment by alexhultman** [comment]
Alright, nothing we can do here.

**Comment by dalisoft** [comment]
Maybe make port on Deno? I think Deno community loves performance and we can affect to Deno performance because Node.js and some others community/organization didn't likes improvements nor performance.

**Comment by alexhultman-2fa** [comment]
Apparently @trevnorris stopped working on nodejs core 3 years ago, and I guess @addaleax took over responsibility for those parts. This maps well with the graph; a slow but sure decline in perf. with every release

**Comment by alexhultman** [comment]
I did manage to reach Trevor Norris on this and he's made a very detail per-commit benchmark and found the most offensive commit in this. That's great but unfortunately Trevor is not working on Node.js anymore, so I don't know if people will listen to him on this.

https://gist.github.com/trevnorris/35c8e570c3097f58739b84bfa3f0a390

**Comment by alexhultman** [comment]
This is the most offending commit: https://github.com/nodejs/node/pull/30959

It's ironic that they claim to have run benchmarks when they **clearly** did not!

**Comment by hst-m** [comment]
Trevor stats for `MakeCallback` match up with uWS.js benchmark

![image](https://user-images.githubusercontent.com/65402951/87204135-f47fab00-c2b8-11ea-9798-4f0cb59fde56.png)

**Comment by alexhultman** [comment]
Problem is, you cannot simply revert that one commit, even though we know exactly where it got messed up. It doesn't revert cleanly since A LOT OF SHIT builds on that large fat commit (it's a squash commit of 30-ish commits where like 8 people have been involved). It's going to take A LOT OF mediating to get this even accepted as an issue - most probably they will just say MEH and continue their entirely pointless tampering with already established fundamentals. Fuck I get so mad at this behavior.

**Comment by alexhultman** [comment]
Community projects without strict meritocracy leads to incompetent people doing incompetent things they shouldn't have the opportunity to do. There is no strong leader, Ryan was at least decently competent but now its just nobodies leading Node.js.
