### ISSUE TITLE
Knowing the state of the socket

### ISSUE THREAD

**Issue by Zaseth** [uNetworking/uWebSockets.js#371]
Hi, awesome module!

Only one question: How do I know the state of the socket (server-side)?

Like, if it's closed or open.

**Comment by alexhultman** [comment]
You can't know that. You have to track it.

However, in practise you can know because all usage of a closed socket will throw an exception. So either track it yourself or rely on this exception.

In C++ you cannot do this, because C++ does not have a garbage collector so the socket dies when it closes so in C++ you _have_ to track it yourself.
