### ISSUE TITLE
Multipart API question

### ISSUE THREAD

**Issue by pavulon** [uNetworking/uWebSockets.js#375]
I wanted to create a PR with updated TypeScript definitions for stuff changed in [v18.7.0](https://github.com/uNetworking/uWebSockets.js/releases/tag/v18.7.0), and I've noticed the new multipart parser `getParts` has quite an interesting API: it returns an array of `Map` objects.

I'd say it is a bit odd, since it's the only function in uWS.js that uses `Map`s, plus it would be a little awkward to use in TS because I think the only way to type it would be `Map<string, ArrayBuffer | string>`. This would require a type guard before accessing any of the values, even though we know that `data` is always an `ArrayBuffer`, and the rest are strings with `name` being the only non-optional one (correct me if I'm wrong).

Are there any reasons why it couldn't be a plain object array?

**Comment by alexhultman** [comment]
Shouldn't Map and Object be the same from a user perspective?

Map is used because V8 docs states it is intended to be faster for this kind of usage, and I have run a benchmark showing a 30% disadvantage, at least, to using Object.

**Comment by alexhultman** [comment]
The problem is that "data" is put in the same container where keys are put, so if a key with name "data" is used that will conflict. Problem is that adding yet another container will harm performance even more since abstractions are costly in scripts.

**Comment by alexhultman** [comment]
Aha! Yeah that could be an object instead. They have data, name, filename, type in a static way.

**Comment by pavulon** [comment]
>Shouldn't Map and Object be the same from a user perspective?

Well, it's a bit different, because you need to use `map.get('data')` instead of `obj.data`. And also as I mentioned, a bit weird to use in TS, because the returned value from `map.get('data')` has a type of `string | ArrayBuffer | undefined`, so I need to check which one is it, before using it. If it were an object, the returned type from `getParts` could be `MultipartField[]`, where `MultipartField` is some thing like
```ts
interface MultipartField {
  name: string;
  data: ArrayBuffer;
  type?: string;
  filename?: string;
}
```
which would be nicer to use.

>Map is used because V8 docs states it is intended to be faster for this kind of usage, and I have run a benchmark showing a 30% disadvantage, at least, to using Object.

Quite interesting. Can't imagine why tho, with such a small number of keys :thinking:

**Comment by alexhultman** [comment]
I see what you say and I agree. I guess I used Map because it was the simplest to do. It should probably be an object since the contents are static.

As I understand it a Map is an Object with static methods (has, get, etc) and when you attach dynamic data to it, you only change internal data (Maps store data logarithmically in a packed array) so there is no changes to the actual object class, it still stays a Map.

With an Object you change the class every time you attach new properties and that apparently fucks the performance up. But for static contents, where you have a static template to clone, it could be better to use Objects I don't know for sure.

**Comment by alexhultman** [comment]
They are objects now so feel free to PR the typedefs
