### ISSUE TITLE
Catching idleTimeout

### ISSUE THREAD

**Issue by Zaseth** [uNetworking/uWebSockets.js#388]
Is there a way to perform a specific action when idleTimeout is performed? For example, I want to be able to send the client a message that they've been kicked for being idle instead of abruptly ending the connection without their knowledge.

**Comment by hst-m** [comment]
I guess it could close with a timeout code/reason rather than close without those? Is it better performance to just close the connection w/o code/reason? I don't need it because clients are sending pings and if it closes it just re-opens, but maybe others could use a timeout code/reason?

**Comment by alexhultman** [comment]
It could be added but I think that is overcomplicating a simple issue. Since idleTimeout is used to **enforce** a particular minimal flow of data, whenever this timeout happens you probably already have backpressure and adding even more backpressure is not ideal. You also have about 55 different cases where proxies and whatnot will drop connections so this isn't really an issue worth making more complicated than what it has to be, because you can never guarantee the connection will in fact receive that close reason. The fact this library even has built-in timeout handling is already covering more than what many other libraries have.
