### ISSUE TITLE
publish/write ordering barrier

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#422]
The documentation currently makes it clear that there are no ordering guarantees between write and publish calls. I assume this is due to performance reasons.

I would like to make a feature request for some kind of barrier function which has a callback that guarantees that all previous writes will be sent before any successive write or publish calls.

e.g.

```js
socket.publish('bar', '123')
socket.flush('bar', () => {
  socket.write('456') // client is guaranteed to receive 123456
})

socket.write('456')
socket.flush(() => {
  socket.publish('foo', '123') // client is guaranteed to receive 123456
})

```

**Comment by hst-m** [comment]
if you need guaranteed order between Send to single socket and Publish you could use Publish instead of Send
```javascript
ws.subscribe(ws.ID)
ws.subscribe('foo')

app.publish(ws.ID,'123')
app.publish('foo','456') // receive 123456
```
Publishing to single socket topic is some amount less performance than ws.send, I have not tested the difference yet, but it will get you guaranteed ordering without need to mess with "flushing" sockets

**Comment by ronag** [comment]
Perfect. Thanks!

**Comment by ronag** [comment]
@hst-m: I assume ordering is guaranteed even between different topics?

**Comment by hst-m** [comment]
yes can review this description of pub/sub here https://github.com/uNetworking/uWebSockets/issues/939#issuecomment-538802292
