### ISSUE TITLE
Github Packages releases

### ISSUE THREAD

**Issue by dtzxporter** [uNetworking/uWebSockets.js#430]
I know npm is off the table, but would you be opposed to releasing on Github Packages repository? It would make it easier to check for updates and quickly install newer versions when released.

**Comment by alexhultman** [comment]
You can star and watch this repository to get notifications of new releases.

> quickly install newer versions when released

This is a horrible idea. You have no warranty or guarantee of any sort. Updating should be done with proper A/B testing or similar, at your own risk.

If you want to always be on latest you can refer to "binaries" branch instead of a specific version. We can add more tags like "stable".

**Comment by alexhultman** [comment]
Okay here is a better answer - 

No for two reasons; 1. we already have an installation process that works and I really feel installation is a "meta"-problem that I do not want to spend more time on. Customers use it and have no issues and using a library requires hours if not days of work to get used to anyways so if installation takes 10 seconds more than what you are used to I honestly do not care.

2 - same reasons as with NPM; this one is political and I could talk about this one for hours and hours. I am a firm believer in capitalism and intellectual properties and ownership and all that follows (except for religion and climate denial) - for me it is entirely madness to agree to be submissive to some third-party enforcer/guardian/parent that have *wildly* different views of ownership than I. My projects are businesses so I want as much control over my property as possible (the fact that these projects are open source is already stretching it pretty damn far - I don't even agree with most open source ideas).

For instance, Apple AppStore, Android PlayStore, PyPi, Microsoft Store, Epic Store, Steam Store <- these are "stores" I could agree to use (even if I dislike the cut they take). NPM, GitHub Packages are "stores" I cannot agree to use.

If you disagree, or don't understand, that's fine but I'm not about to change opinions on this.

**Comment by piranna** [comment]
I TOTALLY disagree with you. You could not agree with the open source philosofy or "stores", but your opinion just only make it more difficult to others. You can be able to publish them on the npm registry by free, but just because you don't like them you don't want to give some effort to do something that can be automated and help others. That's not being capitalism, or at least not in the European interpretation of the word. It could be for USA accepted meaning (that it fits more with neoliberalism), but in any case, in a human sense this behaviour has just only a single description: EGOISM, thinking that your time is more important that others.

You could say "ok, don't use the library", but I'm forced to do so being a dependency of `wt-tracker`, and here I'm wasting my time to fix it because I can't be able to use `ws` instead. It's your project and can do with it whatever you want, and they are your opinions, but they are not fair and your attitude will help anybody.

**Comment by hst-m** [comment]
> That's not being capitalism, or at least not in the European interpretation of the word

So by Capitalism you mean Socialism? Is that how they operate over there? How do you think USA became the most prosperous country on planet, by running socialist policies?

**Comment by piranna** [comment]
> How do you think USA became the most prosperous country on planet, by running socialist policies?

No social security, no public sanity, univesity debs for years, top first world country in number of underage pregnants, jail imprisioned persons, morbid obesity, homeless persons, mass fireguns murderings, lawyers... Sorry, but that's not my definition of a prospeous country, specially regarding to street and social security, but instead as an example of how USA capitalism (AKA anarco-capitalism, or neo-liberalism) and irrational consumism can destroy its citizens. By common world standards, that would be considered a third-world in-development country with a huge use of technology, marketing and international (military) relationships to keep a public image of being a first-world league country. You don't need to take a look on how to do the things right here on Europe socialism (that's NOT social-comunist, a common error there in USA), you can take a look on Canada, it's a lot closser to you and maybe you americans can identify better with them...

**Comment by hst-m** [comment]
USA has 40% larger GDP than all 15 EU countries combined, and has one of the largest GDP per person. Unfortunately we are becoming more socialist so it may not last long

> university debs for years

this is the result of government subsidizing student loans raising prices, the opposite of capitalism

> homeless persons

its a free country, cant force people to work, but also shouldnt provide them with free homes. the question is how do you handle them, left-leaning cities let them roam the streets, right-leaning dont allow it

> no public sanity, underage pregnants, jail imprisioned persons, morbid obesity

we have very large variety of demographics, now you are just hating on the variety of people. Where I live there is much public sanity, no underage pregnant, small amount of crime, and very little obese

**Comment by alexhultman** [comment]
USA is a shit-hole country in many ways I agree, but pretty much the entire world runs on some form of capitalism and all intellectual property laws are designed to accompany capitalism (duh). Most parts of the world agrees with property ownership.

Marxism and class-less no-ownership countries are pretty much hell on earth and the most miserable way of living. The whole problem with class-less ideas is that, while **it sounds excellent as an elevator pitch - everyone gets equal**, as soon as you apply 2 brain cells to the problematics you can infer that **the only way to get an uniform population where everyone is equally successful is to remove free will**.

This because stupid people will continue to make stupid decisions that harm their life, while smart people will continue to make smart decisions that will better their lives. The same goes with good looking people vs. ugly people. Tall people vs. short people. It is impossible to get equal outcome in life unless you **enforce people to do what they don't want to** (also known as Gulag camps and mass murderous psychopathic leaders).

The Nazis were some pretty mean people but the total frag count of the Communists are HUNDREDS OF MILLIONS MORE.

Look at what happened when Soviet fell - every citizen got their equal share of stocks for the state properties. Smart people kept their share and bought more stocks while stupid people sold their stocks. Now the trillionaires of Russia are the people who kept their stocks while the poor are the ones who immediately sold their for an instant satisfaction.

-----

Anyways - 

@piranna Your argumentation is pretty much the same exact one regarding CMake; "follow my religion or else!"

> but **I'm** forced to do so being a dependency of wt-tracker, and here **I'm** wasting my time to fix it because **I can't** be able to use ws instead.

That's a lot of "me me me".

> EGOISM, thinking that your time is more important that others.

Ah yes **I am** an egoist, for not making **your** life easier, acording to what **you** consider easier. For free. Ah yes, let me just risk my whole business by agreeing to indemnification clauses only so that you can run "npm install uws" instead of "npm install uNetworking/uWebSockets.js" because that is SOOOO HAAAARD to do!

What a **total egoist** I am for not publishing my code for free, on the platform of your particular interest. Because moving 3 files from one location to node_modules is soooooooooooooooooo hard! Oh my what a total egoist I am for spending 6 years writing free code that you can run businesses of. I am so fucking horrible of a person for not ALSO doing what YOU want EXTRA for FREE.

Gosh what a HORRIBLE person I am!

**Comment by alexhultman** [comment]
I can say that if anything is going to change - it is going to change to `npm install https://uwebsockets.com/stable`. It is absolutely never going to be `npm install uws`.

**Comment by alexhultman** [comment]
Wait.. we are not even using NPM anymore? It's Yarn, so why the fuck are we even talking about NPM? This whole thing is a non-duscussion.

**Comment by hst-m** [comment]
I dont like using separate library to install so I use npm. If you get this working with Deno there is no package manager, you just do: 
```javascript
import { uWS } from 'https://uwebsockets.com/stable'
```
