### ISSUE TITLE
Binaries for musl?

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#474]
Hi,
Is it possible to provide prebuilt binaries for alpine linux (musl)?

**Comment by alexhultman** [comment]
Hello,

Anything is possible but not everything is sustainable. Muslc is not even officially supported by Node.js itself and there is no reason for it to be. Muslc is an embedded, minimal libc that is aimed at embedded development with C. It has **absolutely no benefits** to high level scripting environments that require tens of megabytes of RAM just to even idle - in fact I am quite certain glibc is faster than muslc on big servers.

**Comment by alexhultman** [comment]
One example is glibc's memchr which drives the HTTP parser of uWS - glibc is really, really fast here and that's why we get really good performance. I'm almost entirely sure performance would go to shit with muslc since **embedded, small size libraries typically do not have multiple executions paths** depending on machine being used.

**Comment by zdm** [comment]
Thank you for reply.
We are trying to make our docker containers smaller. Migration to alpine will allow to decrease size by 200M.
Yes, you are right, node has no official support for musl.
Sorry for disturbing you.

**Comment by alexhultman** [comment]
Decreasing docker container size has nothing with glibc or muslc to do. I can easily create a 20MB docker container with a full on glibc project inside.

There are more alternatives than just either a full on Ubuntu dist or an Alpine dist.
