### ISSUE TITLE
Handle parsing or validation of content-type in C++

### ISSUE THREAD

**Issue by jmealo** [uNetworking/uWebSockets.js#496]
Hello! I hope that you are well. I was wondering if you had any opinion or thoughts on adding parsers or validators that run before v8? Is this a good/bad idea? I'm willing to give it a go :)

Have a great weekend!

**Comment by alexhultman** [comment]
Hi, In a perfect world, nothing would be written in scripting languages but this is not a perfect world and this project needs to draw a line where its scope ends. "Validating" content-type is more of an application level thing, if anything, IMO?

And even if this thing would be added to the scope, people would still find other ways to completely ruin performance, anyways.

**Comment by jmealo** [comment]
Hm.... true true. I was thinking it might be interesting to use simdjson to validate JSON or UTF-8 just for fun.

One use case would be a websocket or http based gateway to NATS. If there's a fast way to get a byte length and a buffer that plus your URI is all you need to craft a NATS protocol message.

If you could make sure everything over the wire is JSON but you don't really need to parse it, I think simdjson's validation only and lazy modes could be a good fit.

I read somewhere that rapidjson is faster than strlen() so I've always wanted to put it to the test somewhere it makes some sense; now simdjson makes me want to try even more 😂

**Comment by alexhultman-2fa** [comment]
strlen is probably slower for large data since libc does not know any info about the memory and cannot use SIMD in any way since it cannot know if it is allowed to read more than 1 byte, so I guess that claim is true.

But you can easily swap it for memchr which will use SIMD since you give libc information about how long the string is so it can use SIMD.

In any case - JSON is out of scope for this project - just like PNG images are and video files and whatnot. This project only cares about the underlying I/O, making it simple to use and fast.
