### ISSUE TITLE
PubSub info

### ISSUE THREAD

**Issue by markmcdowell** [uNetworking/uWebSockets.js#57]
Hello, this library is awesome and I'm getting great performance (even from my macbook 70k/s HTTP GET).

I've been trying out the new `ws.publish` `ws.subscribe` functions but I haven't been able to get them to work. Even using the [PubSub.js](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js) example I don't get any errors but nothing is sent on the websocket.

I'm assuming it's because I'm running on a mac, any ideas to narrow down? (I've tried running in a docker container as well but I get the same results, nothing published on the socket).

**Comment by alexhultman** [comment]
It is disabled for now, will continue with it after a few releases

**Comment by markmcdowell** [comment]
aha, thanks

**Comment by PeterHewat** [comment]
Hello Alex,
I've had the exact same issue.
Good to know you will be implementing it soon.
In the meantime, maybe adding to the documentation the comment "not implemented yet" the same way you have done with the unsubscribe call would help clear the confusion ;-)

**Comment by mattiasewers** [comment]
@alexhultman any news on this? what is the performance like?

**Comment by PeterHewat** [comment]
@mattiasewers Not sure you are going to get a reply from @alexhultman since this issue is closed. That and I don't think he gives deadlines to non paying users.
But FYI, pub/sub is implemented in uWebSockets, not uWebSockets.js
Work has apparently started in [v0.15](https://github.com/uNetworking/uWebSockets/releases/tag/v0.15
)
But the only changes regarding this feature I have seen gone by are:
https://github.com/uNetworking/uWebSockets/commit/f08bc8cd03477460bc4a0511afc3ebe7106cef1e
https://github.com/uNetworking/uWebSockets/commit/6fe717f46a0f4188e1fc929776d1b86791ec7cb0
I guess we just have to wait & see...

**Comment by alexhultman-2fa** [comment]
pub/sub is up and running in v18+
