### ISSUE TITLE
FreeBSD + uWebSockets.js

### ISSUE THREAD

**Issue by sturican** [uNetworking/uWebSockets.js#616]
Hello! 
How is possible build uWebSockets.js on FreeBSD system?
On start app error:
```
node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_freebsd_x64_93.node'
```

Downloaded repo source and run make:

**uWebSockets.js# make**
```
cc build.c
build.c:115:11: error: use of undeclared identifier 'OS'
          OS,
          ^
build.c:119:100: error: use of undeclared identifier 'OS'
    build("aarch64-linux-gnu-gcc", "aarch64-linux-gnu-g++", "-static-libstdc++ -static-libgcc -s", OS, "arm64");
                                                                                                   ^
2 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/local/www/src/uWebSockets.js
```

**Comment by joshxyzhimself** [comment]
Related https://github.com/uNetworking/uWebSockets.js/issues/567

**Comment by sturican** [comment]
No plans for FreeBSD support?

**Comment by alexhultman** [comment]
FreeBSD is not even supported by Node.js themselves; https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list

We rely on an official ABI and therefore we can only support Tier 1 platforms (Linux, Windows, Macos). That's also why we cannot support muslc platforms like Alpine because they simply are not following the official ABI.

You can always try and figure it out yourself and PR needed changes but FreeBSD is not really priority either way
