### ISSUE TITLE
Add self-hosted ARM64 Linux runner

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets.js#645]
Note to self: Instead of fiddling with cross-compilation it looks way easier to just add a Raspberry Pi as self-hosted runner to GH Actions.

**Comment by foogazy** [comment]
Hello and I hope you are well. 

First of all, I cannot thank you enough for this amazing library. It's truly amazing. 

In terms of cross-compilation, I was wondering if I can help with anything since I tried to set it up via this github action (https://github.com/uraimo/run-on-arch-action) but unfortunately this throws SSL errors on arm64 image of their containers  (I don't know what causes this - this probably is the github action's problem) but maybe we can build a (pre-setup) Docker container for github actions to automate the pipeline? 

I'd love to hear your thought on this, since we are currently compiling on our own machine for arm64 but it would be amazing if we can have an automated pipeline for this (Like v18). 

Many thanks in advance.
