### ISSUE TITLE
Means to throttle file upload with onData

### ISSUE THREAD

**Issue by Napzu** [uNetworking/uWebSockets.js#648]
Is there way to throttle file upload with onData?

**Comment by alexhultman** [comment]
Nope, that's actually not possible with SSL so we do not support it for TCP either. Problem with SSL is that TCP is 2 streams while SSL is 1 stream so you can only throttle BOTH or NONE, but that has problems since SSL can write when reading and read when writing so you can end up with "deadlocks" if you expect to only throttle data receives. So the decision was to not support throttling.

This is probably much better in QUIC.

**Comment by alexhultman** [comment]
See linked issue
