### ISSUE TITLE
remove header (uWebSockets)

### ISSUE THREAD

**Issue by hosseinhojjatyar** [uNetworking/uWebSockets.js#703]
Hi,
How can I remove header (uWebSockets) in API response?

**Comment by e3dio** [comment]
Compile with option to remove https://github.com/uNetworking/uWebSockets/blob/eea4b7e0f6e907646d34909e32f415c2a7dea385/src/HttpResponse.h#L87 or a proxy can remove it

**Comment by a-tonchev** [comment]
It would be nice to have option to disable it per default without compiling

**Comment by alexhultman** [comment]
uWS has a header and you cannot remove it unless you configure and compile your own binary. This is a marketing and financial decision that's **not up for discussion**. You can also remove it in your proxy if you want to.

**Comment by dioptre** [comment]
This is a potential security vulnerability - can we remove this by default?

**Comment by uNetworkingAB** [comment]
> Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) 
AppleWebKit/535.19 (KHTML, like Gecko) 
Chrome/18.0.1025.133 Mobile Safari/535.19

Every browser on the internet send this info to every website you visit.

The fact **we** send the name of the server and the major version (20) is not even remotely a security issue, esp. not since we actually do seriously thorough security hammering 24/7 with fuzzing and there are no known cves.

Any schmuck can guess your server software anyways, given one two three guesses - heck most companies even list their tech stack as part of their career page or blog page. So the argument that putting a tag on traffic would be a security issue is really not the analysis I do. Any bot could easily try a list of known security issues regardless of whether the server tells its brand or not. A bot can do hundreds of tries per second, and find its target anyways.

It doesn't really matter what your opinion is anyways, since the cost/benefit analysis greatly tilt in the favor of having the tag. The fact we can identify big companies using our software has literally saved this entire project from certain bankruptcy. So you can either have a bankrupt project without a tag, or a well functioning project with a tag.
