### ISSUE TITLE
User defined allocator

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#813]
It would be great if I could pass a Buffer and/or allocator to uws which will decide where the messages will be written. That way I can avoid doing an additional copy when passing it on to WASM, i.e. in this case I would pass it a buffer allocated from the WASM context.

**Comment by uNetworkingAB** [comment]
That's not compatible with the architecture. We require at least one copy but given how 50% of performance is lost on first jump into JavaScript this copy is negligible

**Comment by ronag** [comment]
> We require at least one copy 

I'm aware of that. The WASM code would do the copy. Right now I have to copy from uws => wasm => user, I want to avoid one of those copies if possible.

Also as another optimization, it would be nice if we could receive multiple messages in a single C++ to JS call.

**Comment by uNetworkingAB** [comment]
You're basically looking for proactor pattern but this project is inherently reactor. But it doesn't matter because none of this will matter in relation to the massive performance penalty you take in JavaScript.

I just today did a new measurement and I lose at least 50% maybe even 60% of performance when involving Node.js so again, performance tweaks at this scale are entirely pointless in this context
