### ISSUE TITLE
Perhaps be a little more relax about nodejs version deprecation?

### ISSUE THREAD

**Issue by markg85** [uNetworking/uWebSockets.js#901]
Hi,

[v20.22.0](https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.22.0) removed nodejs 19 support.
Now it's great that a project is trying to keep up to date with the latest and greatest! Definitely keep doing that!

But... I'd argue that you might be moving just a little too fast and break a little too easy.
Case in point, i'm using arch linux. That is a very actively up to date release. Yet uWebSockets.js manages to break time and time again because arch isn't "that" instant with nodejs updates (it's on 20.1 in testing, release is on 19.9). It only takes a couple weeks - at most - for that to propagate to the main release at which point it all would work just fine.

If my math is about right, you removed support for v19 roughly 1 week after 20.0 was released. Please relax that a little to 1 or 2 months if possible.

Thanx,
Mark

**Comment by porsager** [comment]
I didn't mean something specifically wrong with arch, just suggesting using something that was tied to the even releases if possible :)

**Comment by markg85** [comment]
That is entirely possible but just complicates things perhaps needlessly too. In this specific case it's just a pet project i'm running locally. I could use docker and go the LTS route, sure, but that's quite a bit more complicated. In fact, i'm better off just being annoyed by the breakage, finding the release that still had support and installing that instead (like i did now) ;)

In general though, if this were to be a local dev for something running in production (which it's not) then going the docker route + LTS is the way to go! Just not in this specific case.

**Comment by uNetworkingAB** [comment]
Why don't you just download the version of Node.js you need, from nodejs.org? There is nothing forcing you to only use whatever Arch ships. Sounds like self inflicted problem to me, esp. since Node.js 19 goes EOL in just 1 month.

Download Node.js and copy it to /usr/bin and now you have what you need.

**Comment by markg85** [comment]
> Download Node.js and copy it to /usr/bin and now you have what you need.

That very suggestion is considered to be a huge NO-GO in the linux world. You should rely on the package manager for things to work smoothly, manually adding things in OS controlled folders is bound to cause troubles sooner or later.

Yes, technically /usr/bin is the user folder and /bin is the OS folder. Still, just don't!

It's better to go the package manager route. 20.1 is in testing already.
All i'm asking is for uwebsockets.js to **not near immediately** kill a nodejs version, give it a couple weeks or even till the EOL time.

**Comment by uNetworkingAB** [comment]
Sounds like fanatically self-inflicted problem to me. I've been programming for Linux since 2004 and I'm well aware of the fanatical stance some people have regarding distros and their package strategy.

Ironically, many distros disregard the Node.js official ABI in favor of their fanatical release schedule, which breaks binaries in stealthily ways. This is why we had to swap from relying on OpenSSL from Node.js, to using our own statically linked BoringSSL since, distros would just break Node.js by overriding Node.js's build with their own crap. This in the name of "we know better", which is inherently authoritarian nonsense.

**Comment by markg85** [comment]
That's selectively true at best.
Arch tries very hard to stay true to upstream (not changing anything if not absolutely needed) and they are doing a very good job at that! If arch has it wrong it's likely that upstream has it wrong or that there is some bigger overarching reason.
I don't know for other distros.

My question is simple. It's your project, you decide what you do with it. Just know that for your project, which is a well used project, it makes sense to handle version removals in a liberate way. More bike-shedding won't help the argument in either direction so just choose what you're going to do.

**Comment by uNetworkingAB** [comment]
> That's selectively true at best.
Arch tries very hard to stay true to upstream (not changing anything if not absolutely needed) and they are doing a very good job at that!

Not really. See attached link for a verbatim replication of mentioned problematics. It's not like I'm pulling things from the butthole, I've seen this first hand many times.

https://bugs.archlinux.org/task/59394

**Comment by uNetworkingAB** [comment]
I'm reading that bug report and I'm just staggered with the neglect and ignorance by Arch package maintainers:

1. They redistribute a product made by someone else.
2. In doing so, they break the entire native programmability feature.
3. When confronted with the problem, they file it under "general gripe" and do nothing
4. They argue that the whole native feature is a "bad feature" (the absolute power corruption and authoritarian mind of this guy!) eve though the guy has no cred or know of the product, whatsoever, he just decided that "yeah that's a bad feature".:
  * "I’m not keen to support a **bad feature** especially if it breaks other things, like Ed25519 support in cozy-desktop communications."
  
  I've been in the Linux universe for more than 20 years and this kind of fanatical repulsion of reality is so typical that I can only laugh about it. They, the Arch authoritarian leaders, have decided what Node.js (a third party product manufactured by a third party company) is supposed to be, and not be. And since their whole package manager system is built to only support 1 version of OpenSSL, they must break things like this. It's so classic, and nostalgic to see this kind of authoritarian override in the Linux fanatical world.

How about this:

1. Let the free market produce products as they wish
2. Don't infringe on the free market's product's featureset by authoritarian intervention in thins one has no fucking competence in
3. Live freely

**Comment by uNetworkingAB** [comment]
From a psychological perspective, this behavior is typical "denial". The problem works like so:

1. Assume Arch package manager is the best system in the world. This assumption will be the **premise** and cannot change, regardless of what reality entails.
2. Introduce a **problem** that challenges the premise, indicating Arch package manager **is not** the best system in the world and has flaws such as breaking ABIs.
3. Because we have a **premise**, and not an open ended **hypothesis**, the problem in step 2 must therefore **be false**.
4. Now problem has been resolved and premise is still true. Typical denial, based on a fanatical premise.

This psychological machinery is something I've seen so many times that I could write a 500 page book on fanatical behavior.


Going back to the problem we have in this very thread; you already know of a solution (download the official binary as released by the original producer), but since you have this idea that, everything must be Arch linux package manager installed, we have a similar self-inflicted problem that is for nobody but yourself to solve.

But rather than accepting the problem - we again use the premise in step 1 to conclude that **other people must change for me**, instead of **adapting to reality**.

I find this whole thread, fascinating, honestly.
