### ISSUE TITLE
20.25 ALIEN MODE error on socket.io setup

### ISSUE THREAD

**Issue by joacub** [uNetworking/uWebSockets.js#907]
if the alien mode is ON this is causing a error when socket.io try to update the request to ws

this is the error and only happens with alien mode active:

```
Error: Using uWS.HttpRequest / uWS.Http3Request past its request handler return is forbidden (it is stack allocated).
```

```js
res.upgrade(
        {
          transport,
        },
        req.getHeader("sec-websocket-key"),
        req.getHeader("sec-websocket-protocol"),
        req.getHeader("sec-websocket-extensions"),
        context
);
```

**Comment by kartikk221** [comment]
To provide more context on above, the code references above is at https://github.com/kartikk221/hyper-express/blob/7bf0cddbdd344ef9112a4a69ea47b58fb90ef85a/src/components/http/Response.js#LL294C10-L294C10 and the tests for the Websocket run fine on M1 MacOS / Linux so I'd assume it will take some stressing or certain conditions to recreate the above.

**Comment by uNetworkingAB** [comment]
You most absolutely should not use this mode with Socket.IO. In fact, you shouldn't even use Socket.IO, full stop. None of this is even remotely relevant to anything uWS.js is to be used for. Just forget it, you aren't the intended use case. Not even close.

**Comment by joacub** [comment]
> You most absolutely should not use this mode with Socket.IO. In fact, you shouldn't even use Socket.IO, full stop. None of this is even remotely relevant to anything uWS.js is to be used for. Just forget it, you aren't the intended use case. Not even close.

This is not relevant to socket.io, that’s the example I put but this is relevant to when using  the method upgrade in that mode.

**Comment by kartikk221** [comment]
Based on the above, I am gonna assume uWS.HttpResponse.upgrade() cannot be called after the initial synchronous execution?

**Comment by joacub** [comment]
> Based on the above, I am gonna assume uWS.HttpResponse.upgrade() cannot be called after the initial synchronous execution?

check this: 
https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Upgrade.js

the upgrade method is called when requested so.... It can be called after not necessarily syncronous. 
That's the example they have and that's exactly what socket.io is doing, but lets forget about socket.io that seems not be liked here (I don't see anything wrong in socket.io btw), the thing is that the example uWebsockets.js has is and can be called after some negotiation or delays in the request and not necessary synchronous, you can also do some handshakes if needed before allow the ws connection and then do the upgrade if the server wants to do it under the before conditions.

So this is very relevant to this module or this mode just simple can not be used that way and the author don't want to use that way and just pass all the pressure after connections are upgrade and do all very simple so they don't have to wait for anything before get back to the client.

**Comment by kartikk221** [comment]
I see but my question is whether the upgrade handler callback can be asynchronous. In the example you provided, the res.upgrade() is synchronously called in the upgrade handler. My question is can we use the asynchronous approach where a res.onAborted() can be bound and then say for example, we do setTimeout(upgradeInHere, 1000) then would the res.upgrade() still work?

There is a fundamental limitation if asynchronous cannot be supported because then HyperExpress has to limit and ensure the user cannot provide an asynchronous handler for the upgrade route nor can the user call res.upgrade() after the synchronous upgrade route handler has returned. Also, async middlewares will also have to be forbidden on an upgrade route as we can only do synchronous execution for websocket upgrades it the res.upgrade must be called before the return of the uWS.HttpRequest.

**Comment by joacub** [comment]
yes that is enabled by them, they have an example for async upgrade:

https://github.com/uNetworking/uWebSockets.js/blob/master/examples/UpgradeAsync.js

**Comment by kartikk221** [comment]
I see, so that means Alien mode breaks asynchronous Websocket upgrades? If that is the case, then I'll be disabling alien mode going forward with an opt-in for those who wish to do so.

**Comment by uNetworkingAB** [comment]
Your code was always broken, it just didn't manifest before.

Like the error message say, and the docs, and the examples, and the readmore - you cannot use HttpRequest after any kind of async split of any kind. HttpRequest is only available in the immediate first callback.

**Comment by kartikk221** [comment]
@uNetworkingAB I'm not too sure how @joacub is triggering this exception because the thing is If he is using `hyper-express` than HyperExpress does not access or call any method on `uWS.HttpRequest` after the initial synchronous handler callback as that is forbidden. So whatever is triggering the error for @joacub is causing it because he's accessing the `uWS.HttpRequest` from the `Request.raw` property. I don't think we'll be able to figure what's causing this without getting a larger code snippet and context as to how socket.io or @joacub are doing the upgrade and what leads up to it.

**Comment by uNetworkingAB** [comment]
Well it's not a problem you should report here. The rules are very clear and clearly some of you are breaking them.

**Comment by kartikk221** [comment]
Yeah 100% but I was just following up because @joacub made an issue in `hyper-express` repository as well and so just thought it would be helpful for you If I provided context.

**Comment by e3dio** [comment]
He is doing some Frankenstein monster app of Socket.io + HyperExpress, if you all would just do a normal uWS.js app you would not have these problems

**Comment by kartikk221** [comment]
@e3dio That's exactly where I was confused, I thought he said there was a bug in `hyper-express` itself but it turns out it has nothing to do with `hyper-express` or `uWebsockets.js`. Just the fact that `req.getHeader()` is being called and `req` is being references in the upgrade is enough sign of that.

**Comment by joacub** [comment]
> He is doing some Frankenstein monster app of Socket.io + HyperExpress, if you all would just do a normal uWS.js app you would not have these problems

yeah, you may be right, but thats the way we have to have more compatibility with other code that we have, the union with hyper-express and socket.io is working nice and having an incredible performance, i maybe doing something after the connection im not sure if im modifying the request after or something, but i dont think so.

we just pass to the socket.io compatibility layer the instance of uws as socket.io has a module for this, im trying to see where is the problem.

Im agree with that mixing we are missing probably all some of the performance that uws offers, but i really can not do anything else at this point as all the code is using socket.io and we have to maintenance this compatibility layer for now.

we are looking to replace them but we dont think we will be able in a short term. Thats also the reason we are using the hyper-express solution as we have many other libraries that relies in the express like code base.

just another comment, socket.io is just doing what the examples here are doing so... i maybe doing something after that is breaking this. ill investigate and report here.

thanks

**Comment by uNetworkingAB** [comment]
> the union with hyper-express and socket.io is working nice and having an incredible performance

Please provide scientific proofs of this. I would very much like to see scientific grounds to what you just said. Please provide your reports.

**Comment by uNetworkingAB** [comment]
Since the age of enlightenment, any shit you say, must be thought as being made up nonsense until proven true with scientific measurements. I know for a fact that Socket.IO performs like absolute horse dick and very far from "incredibly performant".

https://en.wikipedia.org/wiki/Age_of_Enlightenment

**Comment by kartikk221** [comment]
I see, yeah I've never personally worked with socket.io, so can't really comment on how bad it would be but `uWebsockets.js` has been a huge benefit to be able to build something like `hyper-express` and use in my own applications. Particulary, it's great for applications / microservices where a lot of cached in-memory data has to be served and thus the additional throughput comes very handy. Has helped be scale down and handle higher peak loads in a lot of my own software in my business just by switching from `express` and writing `hyper-express` on top of `uWebsockets.js`,

**Comment by uNetworkingAB** [comment]
The problem is that people, generally, can't use their brain in any original way. They can't figure out basic solutions to simple problems, but can only google "express tutorial" and find some page, copy paste some already made boiler plate, then google "express best practises" whereby said "best practises" are then copy-pasted into the app being made, and from there you go.

People can only do what others have said for them to do. Copy paste, in a braindead loop. Why are you even programmers if you can't figure out the most basic levels of how a program functions and make own decisions?

The alternative would be, to stop and just recalibrate your brain the slightest, solving problems in a slightly different way without resorting to "am I doing it like you want me to, daddy?". Use your brain and imagine new ways of doing things, it's not like the Swift, Java and Golang people all have "Express" - they still solve problems, without this copy paste mentality.

I swear today's scripters don't know shit, other than how to google some already made template and just paste it in without even considering what they are doing and how.

**Comment by uNetworkingAB** [comment]
Every time I try to enter the mindset of a scripter, my brain wants to rupture from explosive pressure buildup and I know that my lifetime expectancy, yet again, decreased by another 5 years. Keeping this up I won't make it to 50. I need to stop. I cannot handle this

**Comment by joacub** [comment]
> > the union with hyper-express and socket.io is working nice and having an incredible performance
> 
> Please provide scientific proofs of this. I would very much like to see scientific grounds to what you just said. Please provide your reports.

I will give you a benchmark if this unions, doing really great allowing an amount of request beyond what I though.

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/pubsub-benchmark

You can run this pub/sub benchmark. It cannot stress uWS to any significant amount of CPU-time but it doesn't have to, since the difference with Socket.IO is so unimaginably grand that it makes no difference for the conclusion.

**Comment by joacub** [comment]
> The problem is that people, generally, can't use their brain in any original way. They can't figure out basic solutions to simple problems, but can only google "express tutorial" and find some page, copy paste some already made boiler plate, then google "express best practises" whereby said "best practises" are then copy-pasted into the app being made, and from there you go.
> 
> People can only do what others have said for them to do. Copy paste, in a braindead loop. Why are you even programmers if you can't figure out the most basic levels of how a program functions and make own decisions?
> 
> The alternative would be, to stop and just recalibrate your brain the slightest, solving problems in a slightly different way without resorting to "am I doing it like you want me to, daddy?". Use your brain and imagine new ways of doing things, it's not like the Swift, Java and Golang people all have "Express" - they still solve problems, without this copy paste mentality.
> 
> I swear today's scripters don't know shit, other than how to google some already made template and just paste it in without even considering what they are doing and how.

hahahahahah im 100% agree with you, todays programmers aren't really programmers, they just copy and paste, that totally right.

But I don't think hyper-express is doing that at all, and we are not also doing that at all, we are trying to get things done faster using libraries like socket.io that help us to be more productive, yeah I know we will lost some performance but Bussines does not work only with performance, we need also a ways to do things faster and be more productive.


Btw the example are here does not work properly with alien mode, we can not access getHeader in alien mode as the example here shows, I do understand that, but seems like socket.io don't get it and they are accessing this in their codebase, and again even if they are or not the worse the thing is they are solving people and developers problems.

Yeah maybe the worse or not but works and in our case we are getting a really good performance with this combination thanks to uWebsockets.js, we are trying to remove this but it is really hard to do without rebuild and redo all the code using other approaches that will make us less productive.
