### ISSUE TITLE
503 errors and unclosed connections

### ISSUE THREAD

**Issue by vanchenkin** [uNetworking/uWebSockets.js#922]
We have made a zero-config build with uWebSocket.js:

```
import { Config } from '../../config/envConfig';

import { App, HttpResponse } from '../../uWebSockets.js';

const { Port: port } = Config;

(async () => {
    const wss = App();

    wss.any('/*', (res: HttpResponse) => {
        res.writeStatus('200').end('OK');
    });

    wss.listen(port, () => {});
})();
```

As we can see it produces 5xx:
<img width="175" alt="Снимок экрана 2023-06-09 в 17 21 15" src="https://github.com/uNetworking/uWebSockets.js/assets/31795913/9d4662c9-9303-4922-9f37-6d45e793963f">

An interesting detail: the number of active connections to the instance is equal to the number of 5xx errors. So, it does not close  connections for some reason. 

We thought that it's an infrastructure problem, but then we tried Fastify and there was no active connections or 5xx errors at all.

What are we doing wrong?

versions:
uWebSocket.js: 20.30.0
node: 18.12.1

**Comment by e3dio** [comment]
What is the proxy or infrastructure that is in front of uWS.js that is throwing the 503 errors, and what configuration does it have? What logs is it displaying? What kind of requests are you making? You have `wss` but that is not a ws server that is plain http responding with status 200. You have provided zero useful information

**Comment by uNetworkingAB** [comment]
Sounds like you are using NGINX and that you are running HTTP1.0

**Comment by vanchenkin** [comment]
Thanks for your responses, sorry for the lack of useful information, I will try to provide as much as I can.

1) There are multiple NGINX balancers on the route and an istio-ingress before the instance. I can provide some of the configurations if necessary, but there are many of them, and most of them are basic upstream logic.
2) The logs do not provide any useful information in my opinion. Here is an example: 
```
bytes_received: 	 0 
bytes_sent: 	 95 
drop_ok: 	 false 
environ: 	 prod 
level: 	 INFO 
method: 	 GET 
path: 	 /ws/monitoring/log?&wuid=pfphome|b1e33746eccd301f045fc77520efbbec&message=really%20reconnect%20socket&lvl=error&appId=pfphome&key=connection&reason=reconnectWithTimer&error=none&packageVersion=3.16.1&version=4.115.0 
request_proto: 	 HTTP/1.1 
request_time: 	 0 
response_flags: 	 UC 
status: 	 503
```
3) The requests are simple GET requests with query parameters.
4) Yes, some of the microservices use uWebSocket.js for HTTP requests with a plain 200 OK response. This is one of them, but we have 5xx errors on all that are using uWebSocket.js.

As much as I'm concerned, there should be no 5xx errors and active lasting connections, because thats just simple plain HTTP requests.

Yep, there is NGINX and we are running HTTP/1.1.

Thanks!

**Comment by uNetworkingAB** [comment]
Pretty sure you are sending HTTP1.0 requests or otherwise invalid requests, you should check it on the uWS side with for instance Wireshark or any such tool. Or strace or similar.

**Comment by e3dio** [comment]
> There are multiple NGINX balancers on the route

Multiple Nginx proxies in 1 route plus some unknown istio-ingress. You know that Nginx defaults to Http1.0 for upstream right? You have to specifically set `proxy_http_version 1.1` on the correct instance. And your log you provided is not at the correct point in the route to be helpful, it says response was 503 which means it was not directly in front of uWS because uWS would not return 503. So your log saying http1.1 protocol is not relevant

**Comment by vanchenkin** [comment]
Thanks, I will investigate and return with more information or close the issue

**Comment by e3dio** [comment]
This issue is bug in Istio software as explained in this article https://github.com/uNetworking/uWebSockets.js/discussions/923#discussioncomment-6136103 caused by short (10 second) http timeout

**Comment by vanchenkin** [comment]
While I’m investigating, is there any chance that you would implement the change of the timeout with a parameter?

**Comment by e3dio** [comment]
You should ask Istio to fix the bug, kind of ridiculous to throw 503 errors because they can't correctly handle a connection timing out. Just ignore the errors, looks like the request gets retried

**Comment by uNetworkingAB** [comment]
No. You are looking to change what already works, instead of figuring out what is broken. We are RFC9112 compliant and nobody has had any issues with these values. 10 seconds is the time a connection will wait for a request head. That is absolutely not "short", that's ages and ages for a computer. You have some fault in your proxies most definitely you send http 1.0 like I've said five times now but you won't listen but instead look for ways to forcefully tamper with source because you assume your own set up is pristine. I'm not interested in making source changes because you cannot figure out how to set up a hello world server. It's honestly highly draining to have this talk because you don't listen either way.

Give me a concrete bug report with a clear motivation for why something is broken and provide proof of that claim. Doing so I'll fix the bug.

**Comment by uNetworkingAB** [comment]
It's extremely easy to scientifically debug where the issue is. Start Wireshark and look what uWS is sent and how it responds. Simply posting that finding will immediately tell you exactly what is the issue.

**Comment by e3dio** [comment]
Worth mentioning that the linked article did exactly that with Wireshark and found:

> we were observing Istio attempting to send data on a connection that had been closed by the application.  The Istio team are still working on understanding why that is (likely a race condition between the server sending RST and envoy reusing a connection from its pool)

So that is something to look for

**Comment by uNetworkingAB** [comment]
How is that even a bug? Any proxy that holds a connection either need to use tcp keepalive or send http head or whatever. And if the connection is down it should just reopen it and continue as usual. And when you have real traffic these drops won't happen as you have traffic all the time.

They should use a health check endpoint and check with it every second or so. Or just use TCP keepalive.

**Comment by e3dio** [comment]
You might be able to adjust your settings to prevent issue, see this page and search for `connectTimeout`
https://istio.io/latest/docs/concepts/traffic-management/
![image](https://github.com/uNetworking/uWebSockets.js/assets/85405955/41d14599-d4d3-4aab-af37-b02ab39beeaa)

**Comment by vanchenkin** [comment]
Thanks for the adjustment!
Sorry, but the question was is there any chance that you would implement feature to change this timeout for other reasons(not only my specific issue)?

**Comment by e3dio** [comment]
> Thanks for the adjustment!
Sorry, but the question was is there any chance that you would implement feature to change this timeout for other reasons(not only my specific issue)?

Did you not read the very detailed response to your exact question? The answer was NO. I will provide you a link so you can review again: https://github.com/uNetworking/uWebSockets.js/issues/922#issuecomment-1585102736

Also here are the settings you want, try `tcpKeepalive`: https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-TCPSettings
![image](https://github.com/uNetworking/uWebSockets.js/assets/85405955/10e8fc08-9df8-41ac-81b0-0e968a4ec653)

**Comment by vanchenkin** [comment]
Thanks for your detailed answers. No is no, that’s your right, I will close the issue for now until I find significant reasons to reopen it.

**Comment by uNetworkingAB** [comment]
You really aren't absorbing _anything_ here. It's not a "no" because of some power play. It's a "no" because there was never any reason for it. Your proxy just sucks, plain and simple.

I can definitely make things configurable, but only if there is a motivation. Complexity is the evil of simplicity. The fewer knobs is better, as long as it solves the problem.

The problem here is that you use some unknown proxy that just fails at life.

**Comment by uNetworkingAB** [comment]
Alternatively you can use Unix sockets, we support it

**Comment by vanchenkin** [comment]
> You really aren't absorbing anything here. It's not a "no" because of some power play.

Your motivation is clear.

What should I say to you? That I need to require my company to stop using Istio on thousands of servers with hundreds of people working with infrustructure just because some blazingle fast library can't make one simple configurable parameter, while all other libraries have it? 
It's not some unknown proxy, it's a service mesh being used in hundreds of companies successfully solving their needs. There are lots of people working on this library and you really think they are that stupid and can't solve this _obvious_ bug? 
This talk is toxic and I have no need to continue it.

**Comment by vanchenkin** [comment]
I will check your suggestion with HTTP1.0, really thanks for that. 
Why are you even writing that I'm not listening to you? I said that I will investigate this version. What's wrong?

There are no proofs that my bug is completely the same as in the article. So, no point of making this dialog about Istio.

**Comment by uasan** [comment]
We also have Istio on our projects, I also had 503 which sometimes appeared for unknown reasons, outwardly it looked like freezes and resetting the request by timeout.

The reason was a child's mistake, we performed asynchronous authorization of the user if his session was expired, i.e. we tried to read the request in an asynchronous microtask, the uWS gave an error that we didn’t catch, the node process ended, the docker rebooted, the error logs were reset and we didn’t see anything. So I advise you to look in the code for the place where you are trying to read the request in asynchronous code

**Comment by uNetworkingAB** [comment]
> That I need to require my company to stop using Istio on thousands of servers with hundreds of people working with infrustructure just because some blazingly fast library can't make one simple configurable parameter,

And there we have it. The classic "I'm important bla bla bla". Nobody gives **a shit** about your self perceived superiority. Go fuck off and use something else then. I literally cannot care less about your problems. Doesn't affect anything done here, whatsoever.
