### ISSUE TITLE
How to set status code?

### ISSUE THREAD

**Issue by snowinszu** [uNetworking/uWebSockets.js#973]
I use   response.writeStatus('403').end();   but seems not working

**Comment by uNetworkingAB** [comment]
writeStatus must be first call. You can see the usage in README

**Comment by christian-bromann** [comment]
There is no example in README showing usage of `writeStatus` and its need to be called first.

**Comment by the-lstv** [comment]
You need to call it first because the status is the first thing sent in a HTTP request.
You can't write other data like headers and then the status.

An example HTTP 1.1 request looks like this:
```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 123
...
```

Writes must be done in order (status > headers > body).

[docs](https://unetworking.github.io/uWebSockets.js/generated/index.html)

**Comment by christian-bromann** [comment]
> docs

The docs are unfortunately not very clear about that.

**Comment by uNetworkingAB** [comment]
Agree, it can be written in read more

Den lör 25 jan. 2025 00:30Christian Bromann ***@***.***>
skrev:
